// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         profile_id: "profile_id",
 *         host_pattern: "host_pattern"
 *     }
 */
export interface GatewayRuleCreate {
    profile_id: string;
    host_pattern: string;
    path_pattern?: string | null;
    methods?: string[] | null;
    rate_limit_rpm?: number | null;
    auth_strategy?: IsloApi.AuthStrategySchema | null;
    content_filter?: IsloApi.GatewayRuleCreateContentFilter | null;
    priority?: number;
    action?: IsloApi.GatewayAction;
    provider_key?: string | null;
}
