// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         public_key: "public_key"
 *     }
 */
export interface SshCertificateRequest {
    /** User's SSH public key in OpenSSH format (ssh-ed25519 AAAA...) */
    public_key: string;
}
