// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         webhook_id: "webhook_id"
 *     }
 */
export interface GetIncomingWebhookRequest {
    /** Incoming webhook ID */
    webhook_id: string;
}
