// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         factory: "factory",
 *         name: "name"
 *     }
 */
export interface DeleteFactoryMachineRequest {
    factory: string;
    name: string;
}
