// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         factory: "factory",
 *         name: "name"
 *     }
 */
export interface MachineCreate {
    factory: string;
    capabilities?: MachineCreate.Capabilities.Item[];
    disk_gb?: number;
    environment?: string | null;
    gateway_profile?: string | null;
    lifecycle?: IsloApi.LifecyclePolicy | null;
    memory_mb?: number;
    name: string;
    repos?: IsloApi.ControlPlaneGitSource[];
    schedule?: IsloApi.MachineSchedule;
    vcpus?: number;
}

export namespace MachineCreate {
    export type Capabilities = Capabilities.Item[];

    export namespace Capabilities {
        export const Item = {
            Docker: "docker",
            Ssh: "ssh",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
