// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         factory: "factory",
 *         name: "name"
 *     }
 */
export interface MachineUpdate {
    factory: string;
    name: string;
    capabilities?: MachineUpdate.Capabilities.Item[] | null;
    disk_gb?: number | null;
    environment?: string | null;
    gateway_profile?: string | null;
    lifecycle?: IsloApi.LifecyclePolicy | null;
    memory_mb?: number | null;
    repos?: IsloApi.ControlPlaneGitSource[] | null;
    schedule?: IsloApi.MachineSchedule | null;
    vcpus?: number | null;
}

export namespace MachineUpdate {
    export type Capabilities = Capabilities.Item[];

    export namespace Capabilities {
        export const Item = {
            Docker: "docker",
            Ssh: "ssh",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
