// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id"
 *     }
 */
export interface ListExecSessionsRequest {
    sandbox_id: string;
    /** Only return sessions with activity at or after this timestamp */
    since?: string | null;
}
