// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListKnowledgeRequest {
    level?: IsloApi.KnowledgeLevel | null;
    tag?: string | null;
    repository?: string | null;
    /** Search identifier or body text */
    q?: string | null;
    cursor?: string | null;
    limit?: number;
}
