// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         command_id: "command_id"
 *     }
 */
export interface GetComputeEventRequest {
    command_id: string;
}
