// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         body: {
 *             manifest: {
 *                 job: {
 *                     name: "name"
 *                 },
 *                 run: {
 *                     tasks: [{
 *                             name: "name",
 *                             steps: [{}]
 *                         }]
 *                 }
 *             }
 *         }
 *     }
 */
export interface ValidateJobManifestRequest {
    name: string;
    body: IsloApi.JobDeployRequest;
}
