// This file was auto-generated by Fern from our API Definition.

import type * as Islo from "../index.js";

export interface PaginatedSnapshotResponse {
    items: Islo.SnapshotResponse[];
    total: number;
    limit: number;
    offset: number;
}
