// This file was auto-generated by Fern from our API Definition.

/**
 * Hardware specification of a sandbox.
 */
export interface SandboxSpec {
    vcpus: number;
    memory_mb: number;
    disk_gb: number;
}
