// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface EnvironmentCreate {
    entries?: IsloApi.EnvironmentCreateEntriesItem[];
    is_default?: boolean;
    name: string;
}
