// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_name: "sandbox_name",
 *         port: 1
 *     }
 */
export interface CreateShareRequest {
    sandbox_name: string;
    /** Port to share */
    port: number;
    /** Time-to-live in seconds (1 minute to 7 days). Defaults to 24h. */
    ttl_seconds?: number | null;
}
