// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         share_id: "share_id"
 *     }
 */
export interface DeleteShareRequest {
    /** Sandbox name */
    name: string;
    /** Share ID */
    share_id: string;
}
