// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_name: "sandbox_name",
 *         share_id: "share_id"
 *     }
 */
export interface RevokeShareRequest {
    /** Sandbox name */
    sandbox_name: string;
    /** Share ID */
    share_id: string;
}
