// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         name: "name"
 *     }
 */
export interface CreateSessionRequest {
    /** Sandbox name */
    name: string;
    command?: string[] | null;
    env?: Record<string, string | null> | null;
    name: string;
    ttl?: string | null;
    user?: string | null;
    workdir?: string | null;
}
