// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_name: "sandbox_name",
 *         session: "session"
 *     }
 */
export interface SandboxAttachSessionRequest {
    /** Sandbox name */
    sandbox_name: string;
    /** Session name */
    session: string;
}
