// This file was auto-generated by Fern from our API Definition.

export interface AgentSessionEventResponse {
    actor: string;
    agent_id: string | null;
    body: string;
    cache_creation_input_tokens: number | null;
    cache_read_input_tokens: number | null;
    cwd: string;
    effort: string;
    event_id?: (string | null) | undefined;
    event_type: string;
    harness_name: string;
    input_tokens: number | null;
    is_subagent: boolean;
    json_session_id?: (string | null) | undefined;
    message_type?: (string | null) | undefined;
    model: string;
    output_tokens: number | null;
    parent_session_name: string | null;
    parent_session_path: string | null;
    parent_thread_id?: (string | null) | undefined;
    provider?: (string | null) | undefined;
    request_id?: (string | null) | undefined;
    root_session_name: string;
    root_session_path: string;
    seq?: (number | null) | undefined;
    session_depth: number;
    session_name: string;
    session_path: string;
    timestamp: string;
}
