// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type AgenticTransitionInputInstructions =
    | IsloApi.AgenticTransitionInputInstructions.Knowledge
    | IsloApi.AgenticTransitionInputInstructions.Literal;

export namespace AgenticTransitionInputInstructions {
    export interface Knowledge extends IsloApi.KnowledgeBinding {
        type: "knowledge";
    }

    export interface Literal extends IsloApi.LiteralBinding {
        type: "literal";
    }
}
