// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface AgenticTransitionOption {
    name: string;
    to: string;
    label?: (string | null) | undefined;
    params?: Record<string, IsloApi.AgenticTransitionOptionParamsValue> | undefined;
}
