// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * What an agent step produced, which is a step's output as much as stdout.
 *
 * The runner records the turn in full — assistant text, the structured output
 * validated against the step's `[outputs]` contract, the session it ran in.
 * None of it reached a reader before, so an agent step was the one step in a
 * job whose row could only ever say whether it passed.
 */
export interface AgentResult {
    mode?: (string | null) | undefined;
    harness?: (string | null) | undefined;
    status?: (string | null) | undefined;
    outcome?: (string | null) | undefined;
    agent_session_id?: (string | null) | undefined;
    output_text?: (string | null) | undefined;
    outputs?: (Record<string, (IsloApi.JsonValue | undefined) | null> | null) | undefined;
}
