// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface AgenticTransitionInput {
    id: string;
    from: string;
    instructions: IsloApi.AgenticTransitionInputInstructions;
    options?: IsloApi.AgenticTransitionOption[] | undefined;
    label?: (string | null) | undefined;
}
