// This file was auto-generated by Fern from our API Definition.

/**
 * Agent session summary, aggregated from trace events.
 */
export interface AgentSessionResponse {
    session_path: string;
    session_name: string;
    parent_session_path: string | null;
    parent_session_name: string | null;
    root_session_path: string;
    root_session_name: string;
    is_subagent: boolean;
    session_depth: number;
    agent_id: string | null;
    child_count: number;
    first_timestamp: string;
    last_timestamp: string;
    event_count: number;
    model: string;
    total_input_tokens: number;
    total_output_tokens: number;
    cwd: string;
    git_branch: string;
    harness_name: string;
    total_cache_creation_tokens: number;
    total_cache_read_tokens: number;
    first_user_text: string;
}
