// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Durable external resource created or materially changed by a job step.
 */
export interface ArtifactRef {
    /** Stable provider-specific identity */
    external_ref: IsloApi.ArtifactRefExternalRef;
    /** Provider-specific details that are not identity */
    metadata?: Record<string, unknown> | undefined;
    /** What the step did, such as created, updated, or published */
    operation?: (string | null) | undefined;
    /** Must match external_ref.provider */
    provider: string;
    status?: (string | null) | undefined;
    title?: (string | null) | undefined;
    /** Resource type, normally external_ref.kind */
    type: string;
    /** Canonical resource URL */
    url?: (string | null) | undefined;
}
