// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Stable provider-specific identity
 */
export type ArtifactRefExternalRef =
    | IsloApi.ArtifactRefExternalRef.Github
    | IsloApi.ArtifactRefExternalRef.Islo
    | IsloApi.ArtifactRefExternalRef.Linear
    | IsloApi.ArtifactRefExternalRef.Slack
    | IsloApi.ArtifactRefExternalRef.Url;

export namespace ArtifactRefExternalRef {
    export interface Github extends IsloApi.GitHubExternalRef {
        provider: "github";
    }

    export interface Islo extends IsloApi.IsloKnowledgeItemExternalRef {
        provider: "islo";
    }

    export interface Linear extends IsloApi.LinearExternalRef {
        provider: "linear";
    }

    export interface Slack extends IsloApi.SlackMessageExternalRef {
        provider: "slack";
    }

    export interface Url extends IsloApi.UrlExternalRef {
        provider: "url";
    }
}
