// This file was auto-generated by Fern from our API Definition.

export interface AuthStrategySchema {
    mode: AuthStrategySchema.Mode;
    username?: (string | null) | undefined;
    name?: (string | null) | undefined;
    format?: (string | null) | undefined;
}

export namespace AuthStrategySchema {
    export const Mode = {
        Bearer: "bearer",
        Basic: "basic",
        Header: "header",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
