// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface ByoSetupResponse {
    setup_session_id: string;
    connection_id: string;
    source_kind: IsloApi.ByoSourceKind;
    setup_mode: IsloApi.ByoSetupMode;
    redirect_url: string;
}
