// This file was auto-generated by Fern from our API Definition.

export const ByoSourceKind = {
    Databricks: "databricks",
    Aws: "aws",
} as const;
export type ByoSourceKind = (typeof ByoSourceKind)[keyof typeof ByoSourceKind];
