// This file was auto-generated by Fern from our API Definition.

export const ClientInferenceApi = {
    OpenaiChatCompletions: "openai_chat_completions",
    AnthropicMessages: "anthropic_messages",
} as const;
export type ClientInferenceApi = (typeof ClientInferenceApi)[keyof typeof ClientInferenceApi];
