// This file was auto-generated by Fern from our API Definition.

export interface CloudRoleResponse {
    created_at?: (string | null) | undefined;
    id: string;
    is_enabled: boolean;
    islo_trust_role_arn: string;
    provider: string;
    role_arn: string;
    session_duration_seconds: number;
    type: string;
    updated_at?: (string | null) | undefined;
}
