// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type ComputeEventDetailResponseResult =
    | IsloApi.ComputeEventDetailResponseResult.Agent
    | IsloApi.ComputeEventDetailResponseResult.Empty
    | IsloApi.ComputeEventDetailResponseResult.Exec
    | IsloApi.ComputeEventDetailResponseResult.Sandbox
    | IsloApi.ComputeEventDetailResponseResult.Snapshot;

export namespace ComputeEventDetailResponseResult {
    export interface Agent extends IsloApi.AgentResult {
        type: "agent";
    }

    export interface Empty extends IsloApi.EmptyResult {
        type: "empty";
    }

    export interface Exec extends IsloApi.ExecResult {
        type: "exec";
    }

    export interface Sandbox extends IsloApi.SandboxResult {
        type: "sandbox";
    }

    export interface Snapshot extends IsloApi.SnapshotResult {
        type: "snapshot";
    }
}
