// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface ComputeEventDetailResponse {
    command_id: string;
    action: string;
    success: boolean;
    error_message: string | null;
    error_code?: (string | null) | undefined;
    error_details?: (Record<string, unknown> | null) | undefined;
    started_at: string | null;
    completed_at: string | null;
    session_name?: (string | null) | undefined;
    sandbox_name?: (string | null) | undefined;
    result: IsloApi.ComputeEventDetailResponseResult;
}
