// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type ConditionOperand =
    | IsloApi.ConditionOperand.Literal
    | IsloApi.ConditionOperand.Stage
    | IsloApi.ConditionOperand.Transition
    | IsloApi.ConditionOperand.Trigger;

export namespace ConditionOperand {
    export interface Literal extends IsloApi.LiteralBinding {
        type: "literal";
    }

    export interface Stage extends IsloApi.StageOperand {
        type: "stage";
    }

    export interface Transition extends IsloApi.TransitionOperand {
        type: "transition";
    }

    export interface Trigger extends IsloApi.TriggerOperand {
        type: "trigger";
    }
}
