// This file was auto-generated by Fern from our API Definition.

export interface ContainerRegistryResponse {
    cloud_role_id: string;
    created_at?: (string | null) | undefined;
    id: string;
    is_enabled: boolean;
    provider: string;
    region: string;
    registry_host: string;
    repository_prefixes: string[];
    updated_at?: (string | null) | undefined;
}
