// This file was auto-generated by Fern from our API Definition.

export interface ControlPlaneGitSource {
    branch?: (string | null) | undefined;
    primary?: boolean | undefined;
    repo_url: string;
    target_path?: (string | null) | undefined;
}
