// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Tenant-scoped custom integration spec.
 *
 * The frontend owns slug derivation (live preview matches what's stored).
 * The backend treats ``slug`` as authoritative input and only validates its
 * shape -- it never re-derives. ``name`` is the free-form human label and
 * is allowed to contain anything reasonable.
 */
export interface CustomIntegration {
    auth_method?: IsloApi.AuthMethod | undefined;
    authorization_url?: (string | null) | undefined;
    client_id?: (string | null) | undefined;
    client_secret?: (string | null) | undefined;
    mcp_url?: (string | null) | undefined;
    name: string;
    scopes?: (string[] | null) | undefined;
    slug: string;
    token_url?: (string | null) | undefined;
}
