// This file was auto-generated by Fern from our API Definition.

/**
 * Safe display metadata for unknown URL artifacts.
 */
export interface DisplayHint {
    title?: (string | null) | undefined;
    /** HTTPS-only icon URL for rendering */
    icon_url?: (string | null) | undefined;
    provider_name?: (string | null) | undefined;
}
