// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Everything about reasoning effort, in one place.
 *
 * Deliberately not on `InferenceModelCatalogEntry`: that row exists for gateway
 * egress allowlisting, alias rewriting and billing, and effort is a harness CLI
 * concern with no bearing on any of them.
 */
export interface EffortCatalog {
    levels?: IsloApi.EffortLevelRule[] | undefined;
    aliases?: IsloApi.EffortAlias[] | undefined;
}
