// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface EnvironmentResponse {
    id: string;
    name: string;
    is_default: boolean;
    entries: IsloApi.EnvironmentEntryResponse[];
    created_at: string;
    updated_at: string;
}
