// This file was auto-generated by Fern from our API Definition.

export interface EnvironmentGatewayRuleResponse {
    id: string;
    host_pattern: string;
    path_pattern?: (string | null) | undefined;
    methods?: (string[] | null) | undefined;
    rate_limit_rpm?: (number | null) | undefined;
    auth_strategy?: (Record<string, unknown> | null) | undefined;
}
