// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Structured error response for API clients.
 */
export interface ErrorResponse {
    code: IsloApi.IsloErrorCode;
    message: string;
    hint?: (string | null) | undefined;
    details?: (Record<string, unknown> | null) | undefined;
    request_id?: (string | null) | undefined;
}
