// This file was auto-generated by Fern from our API Definition.

/**
 * Command execution started response.
 *
 * The command runs asynchronously in the sandbox. Poll the result via
 * GET /sandboxes/{name}/exec/{exec_id}.
 */
export interface ExecResponse {
    exec_id: string;
    status: string;
    sandbox_id: string;
}
