// This file was auto-generated by Fern from our API Definition.

/**
 * Exec session summary.
 */
export interface ExecSessionResponse {
    exec_id: string;
    /** True for interactive (WebSocket/PTY) sessions, False for exec (run command, stream output) */
    is_interactive?: boolean | undefined;
    first_timestamp: string;
    last_timestamp: string;
    log_count: number;
    /** First stdin line: user input for interactive sessions, command invocation for exec sessions. */
    first_stdin_line?: string | undefined;
}
