// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface FactoryOverview {
    active: number;
    cancelled: number;
    draft: number;
    factories?: IsloApi.FactoryOverviewItem[] | undefined;
    metrics: IsloApi.FactoryMetricsResponse;
    total: number;
}
