// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface FactoryMetricsResponse {
    active_runs: number;
    cost_cents_24h?: number | undefined;
    daily?: IsloApi.DailyBucket[] | undefined;
    success_rate_24h: number;
    throughput_24h: number;
    timezone?: string | undefined;
    total_jobs?: number | undefined;
    total_lines: number;
    window_end?: (string | null) | undefined;
    window_start?: (string | null) | undefined;
}
