// This file was auto-generated by Fern from our API Definition.

export const GatewayAction = {
    Allow: "allow",
    Deny: "deny",
} as const;
export type GatewayAction = (typeof GatewayAction)[keyof typeof GatewayAction];
