// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type GatewayProfileDetailResponseIntegrationPolicy =
    | IsloApi.GatewayProfileDetailResponseIntegrationPolicy.All
    | IsloApi.GatewayProfileDetailResponseIntegrationPolicy.Custom;

export namespace GatewayProfileDetailResponseIntegrationPolicy {
    export interface All extends IsloApi.AllIntegrationsPolicy {
        mode: "all";
    }

    export interface Custom extends IsloApi.CustomIntegrationsPolicy {
        mode: "custom";
    }
}
