// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface GatewayProfileDetailResponse {
    cloud_role?: (IsloApi.CloudRoleRef | null) | undefined;
    created_at?: (string | null) | undefined;
    default_action: string;
    description?: (string | null) | undefined;
    id: string;
    integration_policy?: IsloApi.GatewayProfileDetailResponseIntegrationPolicy | undefined;
    internet_enabled: boolean;
    is_default: boolean;
    name: string;
    rule_count?: number | undefined;
    rules?: IsloApi.GatewayRuleResponse[] | undefined;
    updated_at?: (string | null) | undefined;
}
