// This file was auto-generated by Fern from our API Definition.

/**
 * A git repository to clone into the sandbox workspace.
 */
export interface GitSource {
    /** Source type discriminator. */
    type?: GitSource.Type | undefined;
    /** Git repository URL (HTTPS) */
    repo_url: string;
    /** Branch/tag/ref to checkout. Defaults to the remote HEAD. */
    branch?: (string | null) | undefined;
    /** Target directory name under /workspace. Defaults to repo name. */
    target_path?: (string | null) | undefined;
}

export namespace GitSource {
    /** Source type discriminator. */
    export const Type = {
        Git: "git",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
