// This file was auto-generated by Fern from our API Definition.

export const HmacAlgorithm = {
    Sha256: "sha256",
} as const;
export type HmacAlgorithm = (typeof HmacAlgorithm)[keyof typeof HmacAlgorithm];
