// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface IncomingWebhookSandboxLifecycle {
    auto_resume?: IsloApi.IncomingWebhookAutoResumePolicy | undefined;
    delete_after?: (number | null) | undefined;
    pause_after?: (number | null) | undefined;
    pause_after_idle?: (number | null) | undefined;
}
