// This file was auto-generated by Fern from our API Definition.

export const IngressEventStatus = {
    Pending: "pending",
    Processing: "processing",
    Delivered: "delivered",
    Failed: "failed",
    Exhausted: "exhausted",
} as const;
export type IngressEventStatus = (typeof IngressEventStatus)[keyof typeof IngressEventStatus];
