// This file was auto-generated by Fern from our API Definition.

/**
 * User-facing init capabilities. Platform init (helpers, gateway proxy, and
 * core) always runs; these select optional setup only.
 */
export const InitCapability = {
    Ssh: "ssh",
    Docker: "docker",
} as const;
export type InitCapability = (typeof InitCapability)[keyof typeof InitCapability];
