// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Information about an available provider.
 */
export interface IntegrationProvider {
    name: string;
    hosts: string[];
    apps: IsloApi.ProviderApp[];
}
