// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * List of integrations (both user and tenant level).
 */
export interface IntegrationListResponse {
    integrations: IsloApi.IntegrationStatus[];
}
