// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface IntegrationTriggerSectionInput {
    filters?: IsloApi.LineConditionInput[] | undefined;
    name: string;
    outputs?: Record<string, IsloApi.TriggerPathBinding> | undefined;
    provider: string;
    selector: IsloApi.IntegrationTriggerSectionInputSelector;
}
