// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Full job.toml manifest (TOML or JSON authoring; stored as JSON).
 */
export interface JobManifestOutput {
    job: IsloApi.JobSection;
    run: IsloApi.RunSectionOutput;
    schedule?: (IsloApi.ScheduleSection | null) | undefined;
    verification?: (IsloApi.VerificationSection | null) | undefined;
}
