// This file was auto-generated by Fern from our API Definition.

export interface JobOutputSpec {
    type: JobOutputSpec.Type;
    items?: (JobOutputSpec.Items | null) | undefined;
    required?: boolean | undefined;
    description?: (string | null) | undefined;
    enum?: (unknown[] | null) | undefined;
    reduce?: JobOutputSpec.Reduce | undefined;
}

export namespace JobOutputSpec {
    export const Type = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
        Array: "array",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const Items = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
    } as const;
    export type Items = (typeof Items)[keyof typeof Items];
    export const Reduce = {
        One: "one",
        Last: "last",
        Collect: "collect",
        Gather: "gather",
    } as const;
    export type Reduce = (typeof Reduce)[keyof typeof Reduce];
}
