// This file was auto-generated by Fern from our API Definition.

export interface JobOutputSpec {
    type: JobOutputSpec.Type;
    items?: (JobOutputSpec.Items | null) | undefined;
    required?: boolean | undefined;
    description?: (string | null) | undefined;
    enum?: (unknown[] | null) | undefined;
}

export namespace JobOutputSpec {
    export const Type = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
        Object: "object",
        Array: "array",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const Items = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
    } as const;
    export type Items = (typeof Items)[keyof typeof Items];
}
