// This file was auto-generated by Fern from our API Definition.

export interface JobParamDefinition {
    name: string;
    /** string | integer | number | boolean */
    type: string;
    required?: boolean | undefined;
    default?: (unknown | null) | undefined;
    description?: (string | null) | undefined;
    pattern?: (string | null) | undefined;
    prefix?: (string | null) | undefined;
    enum?: (unknown[] | null) | undefined;
}
