// This file was auto-generated by Fern from our API Definition.

export interface JobParamSpec {
    type: JobParamSpec.Type;
    items?: (JobParamSpec.Items | null) | undefined;
    required?: boolean | undefined;
    default?: (unknown | null) | undefined;
    description?: (string | null) | undefined;
    pattern?: (string | null) | undefined;
    prefix?: (string | null) | undefined;
    enum?: (unknown[] | null) | undefined;
}

export namespace JobParamSpec {
    export type Type = ("string" | "integer" | "number" | "boolean") | "array";
    export const Items = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
    } as const;
    export type Items = (typeof Items)[keyof typeof Items];
}
