// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface JobRunResponse {
    id: string;
    job_name: string;
    job_version_id: string;
    status: string;
    region: string | null;
    run_params: Record<string, unknown>;
    result_payload: Record<string, unknown> | null;
    step_timeline: IsloApi.JobRunStepTimelineEntry[];
    artifact_refs: IsloApi.ArtifactRef[];
    compute_cost_cents?: number | undefined;
    inference_cost_cents?: number | undefined;
    total_cost_cents?: number | undefined;
    cost_rated_at?: (string | null) | undefined;
    started_at: string | null;
    completed_at: string | null;
    error_message: string | null;
    error_code?: (string | null) | undefined;
    error_details?: (Record<string, unknown> | null) | undefined;
    failure_class?: (string | null) | undefined;
    created_at: string;
}
