// This file was auto-generated by Fern from our API Definition.

export interface JobRunStepTimelineEntry {
    name: string;
    action: string;
    status: string;
    task_name: string;
    started_at?: (string | null) | undefined;
    completed_at?: (string | null) | undefined;
    error_message?: (string | null) | undefined;
    compute_command_id?: (string | null) | undefined;
}
