// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface JobRunResponse {
    id: string;
    job_name: string;
    job_version_id: string;
    status: string;
    region: string | null;
    run_params: Record<string, unknown>;
    step_timeline: IsloApi.JobRunStepTimelineEntry[];
    artifact_refs: Record<string, unknown>[];
    started_at: string | null;
    completed_at: string | null;
    error_message: string | null;
    error_code?: (string | null) | undefined;
    error_details?: (Record<string, unknown> | null) | undefined;
    created_at: string;
}
