// This file was auto-generated by Fern from our API Definition.

export interface JobRunListItem {
    id: string;
    job_name: string;
    job_version_id: string;
    status: string;
    region: string | null;
    step_count: number;
    started_at: string | null;
    completed_at: string | null;
    created_at: string;
    error_message: string | null;
}
