// This file was auto-generated by Fern from our API Definition.

export interface JobRunListItem {
    id: string;
    job_name: string;
    job_version_id: string;
    status: string;
    region: string | null;
    step_count: number;
    compute_cost_cents?: number | undefined;
    inference_cost_cents?: number | undefined;
    total_cost_cents?: number | undefined;
    cost_rated_at?: (string | null) | undefined;
    started_at: string | null;
    completed_at: string | null;
    created_at: string;
    error_message: string | null;
}
