// This file was auto-generated by Fern from our API Definition.

export const JobRunStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type JobRunStatus = (typeof JobRunStatus)[keyof typeof JobRunStatus];
