// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface JobSection {
    /** Job name; must match jobs/<name>/ and deploy path */
    name: string;
    version?: (string | null) | undefined;
    description?: (string | null) | undefined;
    /** Declared run parameters. Reference as {{name}} in manifest strings (substitution and undeclared-reference checks walk the whole manifest, not only step fields). Reserved: {{run_id}}. */
    params?: (Record<string, IsloApi.JobParamSpec | null> | null) | undefined;
}
