// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface JobVersionResponse {
    id: string;
    version_number: number;
    content_hash: string;
    deployed_at: string;
    manifest: IsloApi.JobManifestOutput;
}
