// This file was auto-generated by Fern from our API Definition.

export const KnowledgeLevel = {
    Episodic: "episodic",
    Procedural: "procedural",
    Declarative: "declarative",
} as const;
export type KnowledgeLevel = (typeof KnowledgeLevel)[keyof typeof KnowledgeLevel];
