// This file was auto-generated by Fern from our API Definition.

export interface LineRunDebugEnvironment {
    gateway_profile?: (string | null) | undefined;
    region?: (string | null) | undefined;
    sandbox_name?: (string | null) | undefined;
    snapshot_name?: (string | null) | undefined;
}
