// This file was auto-generated by Fern from our API Definition.

export interface LineRunAskRequest {
    /** Instruction or context for the line run's manager */
    message: string;
    /** Optional Slack thread permalink whose activity status should follow this manager turn */
    origin?: (string | null) | undefined;
}
