// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface LineRunSummary {
    id: string;
    line_name: string;
    line_version_id?: (string | null) | undefined;
    status: string;
    trigger: IsloApi.TriggerSummary;
    region?: (string | null) | undefined;
    run_params?: Record<string, unknown> | undefined;
    stages?: IsloApi.LineRunStageSummary[] | undefined;
    artifact_count?: number | undefined;
    artifacts?: IsloApi.ArtifactSummary[] | undefined;
    compute_cost_cents?: number | undefined;
    inference_cost_cents?: number | undefined;
    total_cost_cents?: number | undefined;
    cost_rated_at?: (string | null) | undefined;
    error_message?: (string | null) | undefined;
    failure?: (IsloApi.LineRunFailure | null) | undefined;
    manager_turns?: IsloApi.ManagerTurnSummary[] | undefined;
    triggered_by_actor?: (Record<string, unknown> | null) | undefined;
    started_at?: (string | null) | undefined;
    completed_at?: (string | null) | undefined;
    created_at: string;
}
