// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface LineRunResponse {
    id: string;
    line_name: string;
    line_version_id: string;
    workflow_run_id: string;
    status: string;
    triggered_by: string;
    trigger_payload: Record<string, unknown>;
    region: string | null;
    run_params: Record<string, unknown>;
    result_payload: Record<string, unknown> | null;
    error_message: string | null;
    iteration_count: number;
    budget_used_usd: string | null;
    retry?: (IsloApi.LineRunRetryAction | null) | undefined;
    events?: IsloApi.LineEventResponse[] | undefined;
    started_at: string | null;
    completed_at: string | null;
    created_at: string;
}
