// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type LineManifestOutputTrigger =
    | IsloApi.LineManifestOutputTrigger.IntegrationTrigger
    | IsloApi.LineManifestOutputTrigger.Manual
    | IsloApi.LineManifestOutputTrigger.Schedule
    | IsloApi.LineManifestOutputTrigger.Webhook;

export namespace LineManifestOutputTrigger {
    export interface IntegrationTrigger extends IsloApi.IntegrationTriggerSectionOutput {
        type: "integration_trigger";
    }

    export interface Manual extends IsloApi.ManualTriggerSection {
        type: "manual";
    }

    export interface Schedule extends IsloApi.ScheduleTriggerSection {
        type: "schedule";
    }

    export interface Webhook extends IsloApi.WebhookTriggerSection {
        type: "webhook";
    }
}
