// This file was auto-generated by Fern from our API Definition.

export interface LineLimitsOutput {
    budget_usd?: (string | null) | undefined;
    max_iterations?: (number | null) | undefined;
    timeout?: (string | null) | undefined;
}
