// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface ListPageCloudRoleResponse {
    items: IsloApi.CloudRoleResponse[];
    next_cursor: string | null;
    total?: (number | null) | undefined;
}
