// This file was auto-generated by Fern from our API Definition.

export interface MachineSchedule {
    cron?: (string | null) | undefined;
    enabled?: boolean | undefined;
    timezone?: string | undefined;
}
