// This file was auto-generated by Fern from our API Definition.

/**
 * One manager turn, projected for a list row.
 */
export interface ManagerTurnSummary {
    workflow_run_id: string;
    state: string;
    started_at?: (string | null) | undefined;
}
