// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type MappingPart = IsloApi.MappingPart.Literal | IsloApi.MappingPart.Source;

export namespace MappingPart {
    export interface Literal {
        type: "literal";
        value: string;
    }

    export interface Source {
        type: "source";
        source: IsloApi.ValueSource;
    }
}
