// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface PaginatedSnapshotResponse {
    items: IsloApi.SnapshotResponse[];
    total: number;
    limit: number;
    offset: number;
}
