// This file was auto-generated by Fern from our API Definition.

export interface PayloadMapping {
    type: PayloadMapping.Type;
}

export namespace PayloadMapping {
    export const Type = {
        Original: "original",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
