// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface RunAgentSessionStepAction {
    /** Session outputs require claude, codex, cursor, or opencode. */
    harness: RunAgentSessionStepAction.Harness;
    model?: (string | null) | undefined;
    model_provider?: (RunAgentSessionStepAction.ModelProvider | null) | undefined;
    /** Reasoning effort token. Requires model. Legal values come from the effort table on GET /inference/models, which is keyed by harness and optionally by model. For cursor the pair also resolves to a real model id, because cursor encodes effort in the id rather than taking a flag. Omit to use the harness default. */
    effort?: (string | null) | undefined;
    prompt?: (IsloApi.RunAgentSessionStepActionPrompt | null) | undefined;
    resume_prompt?: (IsloApi.RunAgentSessionStepActionResumePrompt | null) | undefined;
    knowledge?: (IsloApi.KnowledgeBinding[] | null) | undefined;
    session?: (string | null) | undefined;
    command?: (RunAgentSessionStepAction.Command | null) | undefined;
    /** MCP server descriptors to make available to the agent. Each entry carries a key (unique label) and url (MCP endpoint). Duplicates by key are rejected. */
    mcp?: (IsloApi.McpEntry[] | null) | undefined;
}

export namespace RunAgentSessionStepAction {
    /** Session outputs require claude, codex, cursor, or opencode. */
    export const Harness = {
        Codex: "codex",
        Cursor: "cursor",
        Claude: "claude",
        Opencode: "opencode",
    } as const;
    export type Harness = (typeof Harness)[keyof typeof Harness];
    export const ModelProvider = {
        Islo: "islo",
        IsloInference: "islo_inference",
    } as const;
    export type ModelProvider = (typeof ModelProvider)[keyof typeof ModelProvider];
    export type Command = string[] | string;
}
