// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface RunSectionOutput {
    fail_fast?: boolean | undefined;
    fanout?: boolean | undefined;
    concurrency?: number | undefined;
    /** Working directory for every exec and run_agent step. Defaults to ".". Falls back to run.sandbox.workdir when omitted. */
    workdir?: (string | null) | undefined;
    timeout?: (RunSectionOutput.Timeout | null) | undefined;
    region?: (string | null) | undefined;
    teardown_on_complete?: (boolean | null) | undefined;
    resume_on_start?: (boolean | null) | undefined;
    sandbox?: (IsloApi.SandboxConfig | null) | undefined;
    tasks: IsloApi.TaskOutput[];
}

export namespace RunSectionOutput {
    export type Timeout = string | number;
}
