// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Detailed usage for a specific sandbox.
 */
export interface SandboxUsageDetail {
    sandbox_public_id: string;
    sandbox_name: string;
    vcpus: number;
    memory_mb: number;
    disk_gb: number;
    billable_seconds: number;
    cost_cents: number;
    reality_start: string | null;
    reality_stop: string | null;
    status: IsloApi.SandboxUsageStatus;
}
