// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Sandbox init intent. Omitted typed SDK values should send minimal. Raw requests that omit both init and init_capabilities use legacy full init during migration. Platform init always runs.
 */
export type SandboxCreateInit =
    | IsloApi.SandboxCreateInit.Custom
    | IsloApi.SandboxCreateInit.Full
    | IsloApi.SandboxCreateInit.Minimal;

export namespace SandboxCreateInit {
    export interface Custom extends IsloApi.InitCustom {
        type: "custom";
    }

    export interface Full extends IsloApi.InitFull {
        type: "full";
    }

    export interface Minimal extends IsloApi.InitMinimal {
        type: "minimal";
    }
}
