// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Request to create a new sandbox.
 */
export interface SandboxCreate {
    /** User-friendly sandbox name. If omitted, a random slug is generated. */
    name?: (string | null) | undefined;
    /** Container image to use */
    image?: string | undefined;
    /** Number of vCPUs */
    vcpus?: number | undefined;
    /** Memory in MB */
    memory_mb?: number | undefined;
    /** Disk size in GB */
    disk_gb?: number | undefined;
    /** Tool cache key for golden cache lookup (computed by CLI) */
    cache_key?: (string | null) | undefined;
    /** Environment variables to inject into the sandbox */
    env?: (Record<string, string | null> | null) | undefined;
    /** Working directory relative to /workspace (e.g. 'my-project') */
    workdir?: (string | null) | undefined;
    /** Init capabilities to enable (in addition to Core which always runs). None = all capabilities (default, backward compatible), [] = Core only (minimal init), ['ssh', 'devtools'] = Core + specified capabilities. Valid values: ssh, terminal, devtools, docker. */
    init_capabilities?: (string[] | null) | undefined;
    /** Gateway profile name or ID to apply. Uses tenant default if omitted. */
    gateway_profile?: (string | null) | undefined;
    /** Name of a snapshot to restore from. When set, the VM is created from the snapshot's filesystem. */
    snapshot_name?: (string | null) | undefined;
    /** Repository sources to clone into /workspace after VM init. */
    sources?: (IsloApi.GitSource[] | null) | undefined;
    /** Named setup script steps to execute sequentially after git clones. */
    setup_scripts?: (IsloApi.SetupScript[] | null) | undefined;
}
