// This file was auto-generated by Fern from our API Definition.

/** Status of a sandbox for billing purposes. */
export const SandboxUsageStatus = {
    Running: "running",
    Stopped: "stopped",
} as const;
export type SandboxUsageStatus = (typeof SandboxUsageStatus)[keyof typeof SandboxUsageStatus];
