// This file was auto-generated by Fern from our API Definition.

export interface ScheduleTriggerSection {
    cron: string;
    timezone?: string | undefined;
    inputs?: Record<string, unknown> | undefined;
}
