// This file was auto-generated by Fern from our API Definition.

export const SelectorScope = {
    All: "all",
    Selected: "selected",
} as const;
export type SelectorScope = (typeof SelectorScope)[keyof typeof SelectorScope];
