// This file was auto-generated by Fern from our API Definition.

export interface SetupStepResult {
    name: string;
    script?: (string | null) | undefined;
    status: string;
    stderr?: (string | null) | undefined;
    stdout?: (string | null) | undefined;
}
