// This file was auto-generated by Fern from our API Definition.

export interface ShareResponse {
    created_at: string;
    expires_at?: (string | null) | undefined;
    port: number;
    share_id: string;
    url: string;
}
