// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface SlackChannelSelector {
    kind?: SlackChannelSelector.Kind | undefined;
    scope?: IsloApi.SelectorScope | undefined;
    channels?: string[] | undefined;
}

export namespace SlackChannelSelector {
    export const Kind = {
        Channel: "channel",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
