// This file was auto-generated by Fern from our API Definition.

/**
 * Slack message identity within a channel.
 */
export interface SlackMessageExternalRef {
    kind?: SlackMessageExternalRef.Kind | undefined;
    channel: string;
    ts: string;
}

export namespace SlackMessageExternalRef {
    export const Kind = {
        Message: "message",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
