// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * One compute action per step.
 */
export interface TaskStepOutput {
    name?: (string | null) | undefined;
    workdir?: (string | null) | undefined;
    timeout?: (number | null) | undefined;
    user?: (string | null) | undefined;
    exec?: (TaskStepOutput.Exec | null) | undefined;
    run_agent?: (IsloApi.TaskStepOutputRunAgent | null) | undefined;
    snapshot?: (IsloApi.SnapshotStepAction | null) | undefined;
    pause?: (boolean | null) | undefined;
    resume?: (boolean | null) | undefined;
    delete?: (boolean | null) | undefined;
    upload?: (string | null) | undefined;
    download?: (string | null) | undefined;
}

export namespace TaskStepOutput {
    export type Exec = string[] | string;
}
