// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * One compute action per step.
 */
export interface TaskStepInput {
    name?: (string | null) | undefined;
    workdir?: (string | null) | undefined;
    timeout?: (number | null) | undefined;
    user?: (string | null) | undefined;
    exec?: (TaskStepInput.Exec | null) | undefined;
    run_agent?: (IsloApi.TaskStepInputRunAgent | null) | undefined;
    snapshot?: (IsloApi.SnapshotStepAction | null) | undefined;
    pause?: (boolean | null) | undefined;
    resume?: (boolean | null) | undefined;
    delete?: (boolean | null) | undefined;
    upload?: (string | null) | undefined;
    download?: (string | null) | undefined;
    outputs?: (TaskStepInput.Outputs | null) | undefined;
}

export namespace TaskStepInput {
    export type Exec = string[] | string;
    export type Outputs = string[] | Record<string, IsloApi.StepOutputClaim>;
}
