// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface TemplateResponse {
    content_hash: string;
    created_at: string;
    disk_gb?: (number | null) | undefined;
    environment_name?: (string | null) | undefined;
    gateway_profile_name?: (string | null) | undefined;
    init?: (IsloApi.TemplateResponseInit | null) | undefined;
    lifecycle?: (IsloApi.LifecyclePolicy | null) | undefined;
    memory_mb?: (number | null) | undefined;
    name: string;
    snapshot_name?: (string | null) | undefined;
    sources?: (IsloApi.ControlPlaneGitSource[] | null) | undefined;
    vcpus?: (number | null) | undefined;
    version_number: number;
}
