// This file was auto-generated by Fern from our API Definition.

export interface TemplateListItem {
    created_at: string;
    latest_version_number: number;
    name: string;
    updated_at: string;
}
