// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export interface TenantConfigResponse {
    default_gateway_profile_key: string;
    tier: string;
    limits: IsloApi.TenantLimits;
    suspended: boolean;
}
