// This file was auto-generated by Fern from our API Definition.

export interface TimestampRange {
    gt?: string | undefined;
    gte?: string | undefined;
    lt?: string | undefined;
    lte?: string | undefined;
}
