// This file was auto-generated by Fern from our API Definition.

export interface TriggerEventSummary {
    complete: boolean;
    effect_count: number;
    event_name: string;
    id: string;
    invocation_status: string;
    manager_outcome: string;
    manager_routing?: (Record<string, number | null> | null) | undefined;
    outcome: string;
    provider: string;
    provider_delivery_id: string;
    received_at: string;
}
