// This file was auto-generated by Fern from our API Definition.

export interface TriggerPathBinding {
    path: string;
    type: TriggerPathBinding.Type;
}

export namespace TriggerPathBinding {
    export const Type = {
        TriggerPath: "trigger_path",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
