// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

/**
 * Fallback identity for an artifact represented by a public URL.
 */
export interface UrlExternalRef {
    kind?: UrlExternalRef.Kind | undefined;
    /** Public HTTP(S) URL */
    url: string;
    /** Optional safe display metadata for richer rendering of unknown URL artifacts */
    display_hint?: (IsloApi.DisplayHint | null) | undefined;
}

export namespace UrlExternalRef {
    export const Kind = {
        Url: "url",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
