// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../index.js";

export type ValueSource =
    | IsloApi.ValueSource.Header
    | IsloApi.ValueSource.HeaderParam
    | IsloApi.ValueSource.Query
    | IsloApi.ValueSource.JsonPath
    | IsloApi.ValueSource.RawBody
    | IsloApi.ValueSource.Method
    | IsloApi.ValueSource.Path;

export namespace ValueSource {
    export interface Header {
        source: "header";
        name: string;
    }

    export interface HeaderParam {
        source: "header_param";
        header: string;
        param: string;
    }

    export interface Query {
        source: "query";
        name: string;
    }

    export interface JsonPath {
        source: "json_path";
        path: string;
    }

    export interface RawBody {
        source: "raw_body";
    }

    export interface Method {
        source: "method";
    }

    export interface Path {
        source: "path";
    }
}
