// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ContainerRegistryUpdate {
    id: string;
    repository_prefixes?: string[] | null;
    cloud_role_id?: string | null;
    is_enabled?: boolean | null;
}
