// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "ecr",
 *         registry_host: "registry_host",
 *         cloud_role_id: "cloud_role_id",
 *         region: "region"
 *     }
 */
export interface ContainerRegistryCreate {
    provider: IsloApi.RegistryProvider;
    registry_host: string;
    repository_prefixes?: string[];
    cloud_role_id: string;
    region: string;
}
