// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface ListFactoryLineRunsForLineRequest {
    name: string;
    limit?: number;
    offset?: number;
}
