// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListFactoryLineRunsRequest {
    limit?: number;
    offset?: number;
    cursor?: string | null;
    /** Sort order. Allowed: -created_at, created_at */
    sort?: string | null;
    include?: string | string[];
    status?: string | string[];
    line_name?: string | string[];
    /** created_at range. Operators: gte, gt, lte, lt. Serialized as created_at[gte]=…&created_at[lt]=… */
    created_at?: IsloApi.TimestampRange;
    q?: string | null;
}
