// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as IsloApi from "../../../index.js";

export declare namespace ApiKeysClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * API key management
 */
export class ApiKeysClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ApiKeysClient.Options>;

    constructor(options: ApiKeysClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List all API keys for the tenant.
     *
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.apiKeys.listApiKeys()
     */
    public listApiKeys(
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.ApiKeyResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__listApiKeys(requestOptions));
    }

    private async __listApiKeys(
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.ApiKeyResponse[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api-keys",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.ApiKeyResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api-keys");
    }

    /**
     * Create a new API key for the tenant. The key secret is only returned once.
     *
     * @param {IsloApi.CreateApiKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.NotFoundError}
     * @throws {@link IsloApi.ConflictError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.apiKeys.createApiKey({
     *         name: "name"
     *     })
     */
    public createApiKey(
        request: IsloApi.CreateApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.CreateApiKeyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createApiKey(request, requestOptions));
    }

    private async __createApiKey(
        request: IsloApi.CreateApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.CreateApiKeyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api-keys",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.CreateApiKeyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new IsloApi.NotFoundError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new IsloApi.ConflictError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api-keys");
    }

    /**
     * Get details of a specific API key.
     *
     * @param {IsloApi.GetApiKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.NotFoundError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.apiKeys.getApiKey({
     *         api_key_id: "api_key_id"
     *     })
     */
    public getApiKey(
        request: IsloApi.GetApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.ApiKeyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getApiKey(request, requestOptions));
    }

    private async __getApiKey(
        request: IsloApi.GetApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.ApiKeyResponse>> {
        const { api_key_id: apiKeyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api-keys/${core.url.encodePathParam(apiKeyId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.ApiKeyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new IsloApi.NotFoundError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api-keys/{api_key_id}");
    }

    /**
     * Delete an API key. This cannot be undone.
     *
     * @param {IsloApi.DeleteApiKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.NotFoundError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.apiKeys.deleteApiKey({
     *         api_key_id: "api_key_id"
     *     })
     */
    public deleteApiKey(
        request: IsloApi.DeleteApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteApiKey(request, requestOptions));
    }

    private async __deleteApiKey(
        request: IsloApi.DeleteApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { api_key_id: apiKeyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api-keys/${core.url.encodePathParam(apiKeyId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new IsloApi.NotFoundError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api-keys/{api_key_id}");
    }

    /**
     * Deactivate an API key. It can be reactivated later.
     *
     * @param {IsloApi.DeactivateApiKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.NotFoundError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.apiKeys.deactivateApiKey({
     *         api_key_id: "api_key_id"
     *     })
     */
    public deactivateApiKey(
        request: IsloApi.DeactivateApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.ApiKeyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deactivateApiKey(request, requestOptions));
    }

    private async __deactivateApiKey(
        request: IsloApi.DeactivateApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.ApiKeyResponse>> {
        const { api_key_id: apiKeyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api-keys/${core.url.encodePathParam(apiKeyId)}/deactivate`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.ApiKeyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new IsloApi.NotFoundError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api-keys/{api_key_id}/deactivate",
        );
    }

    /**
     * Reactivate a previously deactivated API key.
     *
     * @param {IsloApi.ActivateApiKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.NotFoundError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.apiKeys.activateApiKey({
     *         api_key_id: "api_key_id"
     *     })
     */
    public activateApiKey(
        request: IsloApi.ActivateApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.ApiKeyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__activateApiKey(request, requestOptions));
    }

    private async __activateApiKey(
        request: IsloApi.ActivateApiKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.ApiKeyResponse>> {
        const { api_key_id: apiKeyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api-keys/${core.url.encodePathParam(apiKeyId)}/activate`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.ApiKeyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new IsloApi.NotFoundError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api-keys/{api_key_id}/activate",
        );
    }
}
