// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "provider"
 *     }
 */
export interface DisconnectIntegrationRequest {
    provider: string;
    level?: IsloApi.IntegrationLevel;
    /** oauth or api_key */
    auth_type?: IsloApi.AuthMethod | null;
}
