// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "provider"
 *     }
 */
export interface DisconnectCustomIntegrationRequest {
    provider: string;
    /** Which token to revoke: 'user' (this user's personal) or 'tenant' (workspace) */
    scope?: IsloApi.IntegrationLevel;
    /** Also remove the Descope outbound app entirely (affects every user in this workspace) */
    delete_app?: boolean;
}
