// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListAllJobRunsRequest {
    limit?: number;
    offset?: number;
    /** Filter by run status */
    status?: IsloApi.JobRunStatus | null;
}
