// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_name: "sandbox_name",
 *         exec_id: "exec_id"
 *     }
 */
export interface GetExecResultRequest {
    /** Sandbox name */
    sandbox_name: string;
    /** Exec ID */
    exec_id: string;
}
