// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id"
 *     }
 */
export interface ListAgentSessionsRequest {
    sandbox_id: string;
    /** Only return sessions with activity at or after this timestamp */
    since?: string | null;
    /** Include child/subagent sessions in addition to root sessions */
    include_subagents?: boolean;
}
