// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSandboxesRequest {
    /** Search by sandbox name (case-insensitive) */
    search?: string | null;
    /** Filter by status (e.g., ?status=running&status=unknown&status=deleted) */
    status?: string[] | null;
    /** Filter sandboxes created on or after this date */
    date_from?: string | null;
    /** Filter sandboxes created on or before this date */
    date_to?: string | null;
    /** Filter by creator. Use 'me' for your own sandboxes. */
    created_by?: string | null;
    /** Max items per page */
    limit?: number;
    /** Number of items to skip */
    offset?: number;
}
