// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         port: 1,
 *         path: "path"
 *     }
 */
export interface SandboxProxyRequest {
    /** Sandbox name */
    name: string;
    /** Target port inside the sandbox VM */
    port: number;
    /** Path suffix forwarded to the VM */
    path: string;
}
