// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         path: "path"
 *     }
 */
export interface SandboxDownloadArchiveRequest {
    /** Sandbox name */
    name: string;
    /** Directory path to archive inside the sandbox */
    path: string;
}
