// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_name: "sandbox_name",
 *         presigned_url: "presigned_url"
 *     }
 */
export interface SaveSnapshotRequest {
    /** Sandbox name */
    sandbox_name: string;
    presigned_url: string;
}
