// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as IsloApi from "../../../index.js";

export declare namespace KnowledgeClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Durable knowledge items (memories, skills, rules, prompts)
 */
export class KnowledgeClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<KnowledgeClient.Options>;

    constructor(options: KnowledgeClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {IsloApi.ListKnowledgeRequest} request
     * @param {KnowledgeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.knowledge.listKnowledge()
     */
    public listKnowledge(
        request: IsloApi.ListKnowledgeRequest = {},
        requestOptions?: KnowledgeClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.PaginatedKnowledgeResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listKnowledge(request, requestOptions));
    }

    private async __listKnowledge(
        request: IsloApi.ListKnowledgeRequest = {},
        requestOptions?: KnowledgeClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.PaginatedKnowledgeResponse>> {
        const { level, tag, repository, q, cursor, limit } = request;
        const _queryParams: Record<string, unknown> = {
            level: level !== undefined ? level : undefined,
            tag,
            repository,
            q,
            cursor,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).control,
                "knowledge",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.PaginatedKnowledgeResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/knowledge");
    }

    /**
     * @param {IsloApi.KnowledgeItemCreate} request
     * @param {KnowledgeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.knowledge.createKnowledge({
     *         slug: "slug",
     *         level: "episodic",
     *         body: "body"
     *     })
     */
    public createKnowledge(
        request: IsloApi.KnowledgeItemCreate,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.KnowledgeItemResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createKnowledge(request, requestOptions));
    }

    private async __createKnowledge(
        request: IsloApi.KnowledgeItemCreate,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.KnowledgeItemResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).control,
                "knowledge",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.KnowledgeItemResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/knowledge");
    }

    /**
     * @param {IsloApi.GetKnowledgeRequest} request
     * @param {KnowledgeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.knowledge.getKnowledge({
     *         identifier: "identifier"
     *     })
     */
    public getKnowledge(
        request: IsloApi.GetKnowledgeRequest,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.KnowledgeItemResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getKnowledge(request, requestOptions));
    }

    private async __getKnowledge(
        request: IsloApi.GetKnowledgeRequest,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.KnowledgeItemResponse>> {
        const { identifier } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).control,
                `knowledge/${core.url.encodePathParam(identifier)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.KnowledgeItemResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/knowledge/{identifier}");
    }

    /**
     * @param {IsloApi.DeleteKnowledgeRequest} request
     * @param {KnowledgeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.knowledge.deleteKnowledge({
     *         identifier: "identifier"
     *     })
     */
    public deleteKnowledge(
        request: IsloApi.DeleteKnowledgeRequest,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteKnowledge(request, requestOptions));
    }

    private async __deleteKnowledge(
        request: IsloApi.DeleteKnowledgeRequest,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { identifier } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).control,
                `knowledge/${core.url.encodePathParam(identifier)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/knowledge/{identifier}");
    }

    /**
     * @param {IsloApi.KnowledgeItemUpdate} request
     * @param {KnowledgeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.knowledge.updateKnowledge({
     *         identifier: "identifier"
     *     })
     */
    public updateKnowledge(
        request: IsloApi.KnowledgeItemUpdate,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.KnowledgeItemResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateKnowledge(request, requestOptions));
    }

    private async __updateKnowledge(
        request: IsloApi.KnowledgeItemUpdate,
        requestOptions?: KnowledgeClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.KnowledgeItemResponse>> {
        const { identifier, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).control,
                `knowledge/${core.url.encodePathParam(identifier)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.KnowledgeItemResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/knowledge/{identifier}");
    }
}
