// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as IsloApi from "../../../index.js";

export declare namespace TenantsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Tenant management
 */
export class TenantsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TenantsClient.Options>;

    constructor(options: TenantsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {TenantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.tenants.listTenants()
     */
    public listTenants(
        requestOptions?: TenantsClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.PublicTenant[]> {
        return core.HttpResponsePromise.fromPromise(this.__listTenants(requestOptions));
    }

    private async __listTenants(
        requestOptions?: TenantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.PublicTenant[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "tenants/",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.PublicTenant[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tenants/");
    }

    /**
     * @param {IsloApi.CreateTenant} request
     * @param {TenantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.tenants.createTenant({
     *         name: "name"
     *     })
     */
    public createTenant(
        request: IsloApi.CreateTenant,
        requestOptions?: TenantsClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.CreateTenantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTenant(request, requestOptions));
    }

    private async __createTenant(
        request: IsloApi.CreateTenant,
        requestOptions?: TenantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.CreateTenantResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "tenants",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.CreateTenantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/tenants");
    }

    /**
     * @param {TenantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.tenants.getSubscription()
     */
    public getSubscription(
        requestOptions?: TenantsClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.PublicSubscription> {
        return core.HttpResponsePromise.fromPromise(this.__getSubscription(requestOptions));
    }

    private async __getSubscription(
        requestOptions?: TenantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.PublicSubscription>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "tenants/subscription",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.PublicSubscription, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tenants/subscription");
    }

    /**
     * Get all tenant settings.
     *
     * @param {TenantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.tenants.getTenantSettings()
     */
    public getTenantSettings(
        requestOptions?: TenantsClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.TenantSettingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTenantSettings(requestOptions));
    }

    private async __getTenantSettings(
        requestOptions?: TenantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.TenantSettingsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "tenants/settings",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.TenantSettingsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tenants/settings");
    }

    /**
     * Partial update tenant settings (deep merge).
     *
     * @param {IsloApi.TenantSettingsUpdate} request
     * @param {TenantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IsloApi.UnauthorizedError}
     * @throws {@link IsloApi.UnprocessableEntityError}
     *
     * @example
     *     await client.tenants.updateTenantSettings({
     *         data: {
     *             "key": "value"
     *         }
     *     })
     */
    public updateTenantSettings(
        request: IsloApi.TenantSettingsUpdate,
        requestOptions?: TenantsClient.RequestOptions,
    ): core.HttpResponsePromise<IsloApi.TenantSettingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateTenantSettings(request, requestOptions));
    }

    private async __updateTenantSettings(
        request: IsloApi.TenantSettingsUpdate,
        requestOptions?: TenantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IsloApi.TenantSettingsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "tenants/settings",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IsloApi.TenantSettingsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IsloApi.UnauthorizedError(
                        _response.error.body as IsloApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new IsloApi.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IsloApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/tenants/settings");
    }
}
