// This file was auto-generated by Fern from our API Definition.

import type * as Islo from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface GatewayProfileCreate {
    name: string;
    description?: string | null;
    default_action?: Islo.GatewayAction;
    internet_enabled?: boolean;
    is_default?: boolean;
}
