// This file was auto-generated by Fern from our API Definition.

import type * as Islo from "../../../../index.js";

/**
 * @example
 *     {
 *         profile_id: "profile_id",
 *         rules: [{
 *                 rule_id: "rule_id",
 *                 priority: 1
 *             }]
 *     }
 */
export interface RuleReorderRequest {
    profile_id: string;
    rules: Islo.RuleReorderItem[];
}
