// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id"
 *     }
 */
export interface SnapshotCreate {
    sandbox_id: string;
    name?: string | null;
}
