// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../index.js";

export type EnvironmentUpdateEntriesItem =
    | IsloApi.EnvironmentUpdateEntriesItem.Secret
    | IsloApi.EnvironmentUpdateEntriesItem.Variable;

export namespace EnvironmentUpdateEntriesItem {
    export interface Secret extends IsloApi.EnvironmentSecretUpdateInput {
        kind: "secret";
    }

    export interface Variable extends IsloApi.EnvironmentVariableInput {
        kind: "variable";
    }
}
