// This file was auto-generated by Fern from our API Definition.

import type * as Islo from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "provider"
 *     }
 */
export interface DisconnectIntegrationRequest {
    provider: string;
    level?: Islo.IntegrationLevel;
}
