// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockIsloAccessKey } from "./mockAuth";

describe("CloudRolesClient", () => {
    test("list_cloud_roles (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                provider: "provider",
                role_arn: "role_arn",
                external_id: "external_id",
                session_duration_seconds: 1,
                is_enabled: true,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        ];

        server.mockEndpoint().get("/cloud-roles").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.cloudRoles.listCloudRoles();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_cloud_roles (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().get("/cloud-roles").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cloudRoles.listCloudRoles();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_cloud_roles (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/cloud-roles").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cloudRoles.listCloudRoles();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("create_cloud_role (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { provider: "aws", role_arn: "role_arn" };
        const rawResponseBody = {
            id: "id",
            provider: "provider",
            role_arn: "role_arn",
            external_id: "external_id",
            session_duration_seconds: 1,
            is_enabled: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/cloud-roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cloudRoles.createCloudRole({
            provider: "aws",
            role_arn: "role_arn",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_cloud_role (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { provider: "aws", role_arn: "x" };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/cloud-roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.createCloudRole({
                provider: "aws",
                role_arn: "x",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_cloud_role (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { provider: "aws", role_arn: "x" };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/cloud-roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.createCloudRole({
                provider: "aws",
                role_arn: "x",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("create_cloud_role (4)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { provider: "aws", role_arn: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/cloud-roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.createCloudRole({
                provider: "aws",
                role_arn: "x",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_cloud_role (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            provider: "provider",
            role_arn: "role_arn",
            external_id: "external_id",
            session_duration_seconds: 1,
            is_enabled: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/cloud-roles/role_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cloudRoles.getCloudRole({
            role_id: "role_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_cloud_role (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .get("/cloud-roles/role_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.getCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("get_cloud_role (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .get("/cloud-roles/role_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.getCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("get_cloud_role (4)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/cloud-roles/role_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.getCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_cloud_role (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/cloud-roles/role_id").respondWith().statusCode(200).build();

        const response = await client.cloudRoles.deleteCloudRole({
            role_id: "role_id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_cloud_role (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .delete("/cloud-roles/role_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.deleteCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("delete_cloud_role (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .delete("/cloud-roles/role_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.deleteCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("delete_cloud_role (4)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/cloud-roles/role_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.deleteCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("update_cloud_role (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            provider: "provider",
            role_arn: "role_arn",
            external_id: "external_id",
            session_duration_seconds: 1,
            is_enabled: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/cloud-roles/role_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cloudRoles.updateCloudRole({
            role_id: "role_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_cloud_role (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .patch("/cloud-roles/role_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.updateCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("update_cloud_role (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .patch("/cloud-roles/role_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.updateCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("update_cloud_role (4)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .patch("/cloud-roles/role_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.updateCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("update_cloud_role (5)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/cloud-roles/role_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cloudRoles.updateCloudRole({
                role_id: "role_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
