// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CreditsClient", () => {
    test("get_credit_balance (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { balance_cents: 1, currency: "currency" };

        server.mockEndpoint().get("/credits/balance").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.credits.getCreditBalance();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_credit_balance (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/credits/balance").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.credits.getCreditBalance();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
