// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EnvironmentsClient", () => {
    test("list_environments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    id: "id",
                    is_default: true,
                    name: "name",
                    secret_count: 1,
                    updated_at: "2024-01-15T09:30:00Z",
                    variable_count: 1,
                },
            ],
            next_cursor: "next_cursor",
            total: 1,
        };

        server
            .mockEndpoint({ once: false })
            .get("/environments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.environments.listEnvironments();

        expect(expected.items).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.items).toEqual(nextPage.data);
    });

    test("list_environments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server.mockEndpoint().get("/environments").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.environments.listEnvironments();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_environments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/environments").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.environments.listEnvironments();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("create_environment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            created_at: "2024-01-15T09:30:00Z",
            entries: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    has_value: true,
                    id: "id",
                    key: "key",
                    kind: "variable",
                    placement: "sandbox_env",
                    rule: { host_pattern: "host_pattern", id: "id" },
                    updated_at: "2024-01-15T09:30:00Z",
                    value: "value",
                },
            ],
            id: "id",
            is_default: true,
            name: "name",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.environments.createEnvironment({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_environment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.createEnvironment({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_environment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.createEnvironment({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("create_environment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.createEnvironment({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("create_environment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.createEnvironment({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_environment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            created_at: "2024-01-15T09:30:00Z",
            entries: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    has_value: true,
                    id: "id",
                    key: "key",
                    kind: "variable",
                    placement: "sandbox_env",
                    rule: { host_pattern: "host_pattern", id: "id" },
                    updated_at: "2024-01-15T09:30:00Z",
                    value: "value",
                },
            ],
            id: "id",
            is_default: true,
            name: "name",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/environments/environment_ref")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.environments.getEnvironment({
            environment_ref: "environment_ref",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_environment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/environments/environment_ref")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.getEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("get_environment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/environments/environment_ref")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.getEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("get_environment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/environments/environment_ref")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.getEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_environment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/environments/environment_ref").respondWith().statusCode(200).build();

        const response = await client.environments.deleteEnvironment({
            environment_ref: "environment_ref",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_environment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.deleteEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("delete_environment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.deleteEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("delete_environment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.deleteEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("update_environment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            created_at: "2024-01-15T09:30:00Z",
            entries: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    has_value: true,
                    id: "id",
                    key: "key",
                    kind: "variable",
                    placement: "sandbox_env",
                    rule: { host_pattern: "host_pattern", id: "id" },
                    updated_at: "2024-01-15T09:30:00Z",
                    value: "value",
                },
            ],
            id: "id",
            is_default: true,
            name: "name",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/environments/environment_ref")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.environments.updateEnvironment({
            environment_ref: "environment_ref",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_environment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/environments/environment_ref")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.updateEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("update_environment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/environments/environment_ref")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.updateEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("update_environment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/environments/environment_ref")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.updateEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("update_environment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/environments/environment_ref")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.updateEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("set_default_environment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            created_at: "2024-01-15T09:30:00Z",
            entries: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    has_value: true,
                    id: "id",
                    key: "key",
                    kind: "variable",
                    placement: "sandbox_env",
                    rule: { host_pattern: "host_pattern", id: "id" },
                    updated_at: "2024-01-15T09:30:00Z",
                    value: "value",
                },
            ],
            id: "id",
            is_default: true,
            name: "name",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/environments/environment_ref/default")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.environments.setDefaultEnvironment({
            environment_ref: "environment_ref",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("set_default_environment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/environments/environment_ref/default")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.setDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("set_default_environment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/environments/environment_ref/default")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.setDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("set_default_environment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/environments/environment_ref/default")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.setDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("unset_default_environment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            created_at: "2024-01-15T09:30:00Z",
            entries: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    has_value: true,
                    id: "id",
                    key: "key",
                    kind: "variable",
                    placement: "sandbox_env",
                    rule: { host_pattern: "host_pattern", id: "id" },
                    updated_at: "2024-01-15T09:30:00Z",
                    value: "value",
                },
            ],
            id: "id",
            is_default: true,
            name: "name",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref/default")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.environments.unsetDefaultEnvironment({
            environment_ref: "environment_ref",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("unset_default_environment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref/default")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.unsetDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("unset_default_environment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref/default")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.unsetDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("unset_default_environment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref/default")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.unsetDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("unset_default_environment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/environments/environment_ref/default")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.environments.unsetDefaultEnvironment({
                environment_ref: "environment_ref",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
