// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FactoryClient", () => {
    test("validate_factory_line_manifest (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                line: { name: "name" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                },
                stages: [{ id: "id", job: "job" }],
            },
        };

        server
            .mockEndpoint()
            .post("/factory/lines/name/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.factory.validateFactoryLineManifest({
            name: "name",
            body: {
                manifest: {
                    line: {
                        name: "name",
                    },
                    trigger: {
                        type: "integration_trigger",
                        provider: "provider",
                        name: "name",
                        selector: {
                            provider: "github",
                        },
                    },
                    stages: [
                        {
                            id: "id",
                            job: "job",
                        },
                    ],
                },
            },
        });
        expect(response).toEqual(undefined);
    });

    test("validate_factory_line_manifest (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                line: { name: "name" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                },
                stages: [
                    { id: "id", job: "job" },
                    { id: "id", job: "job" },
                ],
            },
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/factory/lines/name/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.validateFactoryLineManifest({
                name: "name",
                body: {
                    manifest: {
                        line: {
                            name: "name",
                        },
                        trigger: {
                            type: "integration_trigger",
                            provider: "provider",
                            name: "name",
                            selector: {
                                provider: "github",
                            },
                        },
                        stages: [
                            {
                                id: "id",
                                job: "job",
                            },
                            {
                                id: "id",
                                job: "job",
                            },
                        ],
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("validate_factory_line_manifest (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                line: { name: "name" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                },
                stages: [
                    { id: "id", job: "job" },
                    { id: "id", job: "job" },
                ],
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/factory/lines/name/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.validateFactoryLineManifest({
                name: "name",
                body: {
                    manifest: {
                        line: {
                            name: "name",
                        },
                        trigger: {
                            type: "integration_trigger",
                            provider: "provider",
                            name: "name",
                            selector: {
                                provider: "github",
                            },
                        },
                        stages: [
                            {
                                id: "id",
                                job: "job",
                            },
                            {
                                id: "id",
                                job: "job",
                            },
                        ],
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("deploy_factory_line (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                line: { name: "name" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                },
                stages: [{ id: "id", job: "job" }],
            },
        };
        const rawResponseBody = {
            id: "id",
            version_number: 1,
            content_hash: "content_hash",
            deployed_at: "2024-01-15T09:30:00Z",
            manifest: {
                line: { name: "name", description: "description", category: "category" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                    filters: [{ op: "all", conditions: [] }],
                    outputs: { key: { type: "trigger_path", path: "path" } },
                },
                stages: [{ id: "id", job: "job" }],
                transitions: [
                    {
                        type: "agentic",
                        id: "id",
                        from: "from",
                        instructions: { type: "knowledge", slug: "slug" },
                        options: [{ name: "name", to: "to" }],
                    },
                ],
                agent: { instructions: { type: "knowledge", slug: "slug" } },
                limits: { max_iterations: 1, budget_usd: "budget_usd", timeout: "timeout" },
            },
            input_params: [
                {
                    name: "name",
                    type: "string",
                    items: "string",
                    required: true,
                    default: { key: "value" },
                    description: "description",
                    pattern: "pattern",
                    prefix: "prefix",
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/factory/lines/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.deployFactoryLine({
            name: "name",
            body: {
                manifest: {
                    line: {
                        name: "name",
                    },
                    trigger: {
                        type: "integration_trigger",
                        provider: "provider",
                        name: "name",
                        selector: {
                            provider: "github",
                        },
                    },
                    stages: [
                        {
                            id: "id",
                            job: "job",
                        },
                    ],
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deploy_factory_line (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                line: { name: "name" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                },
                stages: [
                    { id: "id", job: "job" },
                    { id: "id", job: "job" },
                ],
            },
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/factory/lines/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.deployFactoryLine({
                name: "name",
                body: {
                    manifest: {
                        line: {
                            name: "name",
                        },
                        trigger: {
                            type: "integration_trigger",
                            provider: "provider",
                            name: "name",
                            selector: {
                                provider: "github",
                            },
                        },
                        stages: [
                            {
                                id: "id",
                                job: "job",
                            },
                            {
                                id: "id",
                                job: "job",
                            },
                        ],
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("deploy_factory_line (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                line: { name: "name" },
                trigger: {
                    type: "integration_trigger",
                    provider: "provider",
                    name: "name",
                    selector: { provider: "github" },
                },
                stages: [
                    { id: "id", job: "job" },
                    { id: "id", job: "job" },
                ],
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/factory/lines/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.deployFactoryLine({
                name: "name",
                body: {
                    manifest: {
                        line: {
                            name: "name",
                        },
                        trigger: {
                            type: "integration_trigger",
                            provider: "provider",
                            name: "name",
                            selector: {
                                provider: "github",
                            },
                        },
                        stages: [
                            {
                                id: "id",
                                job: "job",
                            },
                            {
                                id: "id",
                                job: "job",
                            },
                        ],
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_factory_lines (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                description: "description",
                status: "status",
                category: "category",
                stage_count: 1,
                trigger_type: "trigger_type",
                latest_version_number: 1,
                resolved_stages: [{ id: "id", job: "job" }],
                created_at: "2024-01-15T09:30:00Z",
                latest_version: {
                    id: "id",
                    version_number: 1,
                    content_hash: "content_hash",
                    deployed_at: "2024-01-15T09:30:00Z",
                    manifest: {
                        line: { name: "name" },
                        trigger: {
                            type: "integration_trigger",
                            provider: "provider",
                            name: "name",
                            selector: { provider: "github" },
                        },
                        stages: [{ id: "id", job: "job" }],
                    },
                    input_params: [{ name: "name", type: "string" }],
                },
            },
        ];

        server.mockEndpoint().get("/factory/lines").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.factory.listFactoryLines();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_factory_lines (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/factory/lines").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.factory.listFactoryLines();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_factory_line (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            status: "status",
            category: "category",
            stage_count: 1,
            trigger_type: "trigger_type",
            latest_version_number: 1,
            resolved_stages: [
                {
                    id: "id",
                    job: "job",
                    description: "description",
                    kind: "agent",
                    harness: "codex",
                    agent_model: "agent_model",
                    agent_role: "agent_role",
                    runtime: "runtime",
                },
            ],
            created_at: "2024-01-15T09:30:00Z",
            latest_version: {
                id: "id",
                version_number: 1,
                content_hash: "content_hash",
                deployed_at: "2024-01-15T09:30:00Z",
                manifest: {
                    line: { name: "name" },
                    trigger: {
                        type: "integration_trigger",
                        provider: "provider",
                        name: "name",
                        selector: { provider: "github" },
                    },
                    stages: [{ id: "id", job: "job" }],
                    transitions: [
                        {
                            type: "agentic",
                            id: "id",
                            from: "from",
                            instructions: { type: "knowledge", slug: "slug" },
                            options: [{ name: "name", to: "to" }],
                        },
                    ],
                },
                input_params: [{ name: "name", type: "string" }],
            },
        };

        server
            .mockEndpoint()
            .get("/factory/lines/name")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.getFactoryLine({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_factory_line (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/lines/name")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.getFactoryLine({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_factory_line_versions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                version_number: 1,
                content_hash: "content_hash",
                deployed_at: "2024-01-15T09:30:00Z",
                manifest: {
                    line: { name: "name" },
                    trigger: {
                        type: "integration_trigger",
                        provider: "provider",
                        name: "name",
                        selector: { provider: "github" },
                    },
                    stages: [{ id: "id", job: "job" }],
                    transitions: [
                        {
                            type: "agentic",
                            id: "id",
                            from: "from",
                            instructions: { type: "knowledge", slug: "slug" },
                            options: [{ name: "name", to: "to" }],
                        },
                    ],
                },
                input_params: [{ name: "name", type: "string" }],
            },
        ];

        server
            .mockEndpoint()
            .get("/factory/lines/name/versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.listFactoryLineVersions({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_factory_line_versions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/lines/name/versions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.listFactoryLineVersions({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_factory_line_runs_for_line (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                line_name: "line_name",
                line_version_id: "line_version_id",
                status: "status",
                trigger: {
                    source: "source",
                    provider: "provider",
                    event_name: "event_name",
                    delivery_id: "delivery_id",
                    payload: { key: "value" },
                },
                region: "region",
                run_params: { key: "value" },
                stages: [{ stage_name: "stage_name", stage_order: 1, iteration: 1, status: "status" }],
                artifact_count: 1,
                artifacts: [{}],
                error_message: "error_message",
                failure: {
                    code: "manifest_no_stages",
                    domain: "platform",
                    error_code: "error_code",
                    failure_class: "failure_class",
                    error_message: "error_message",
                    error_details: { key: "value" },
                    stage_name: "stage_name",
                    stage_step: "stage_step",
                    task_name: "task_name",
                },
                started_at: "2024-01-15T09:30:00Z",
                completed_at: "2024-01-15T09:30:00Z",
                created_at: "2024-01-15T09:30:00Z",
            },
        ];

        server
            .mockEndpoint()
            .get("/factory/lines/name/runs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.listFactoryLineRunsForLine({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_factory_line_runs_for_line (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/lines/name/runs")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.listFactoryLineRunsForLine({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("trigger_factory_line_run (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            line_name: "line_name",
            line_version_id: "line_version_id",
            workflow_run_id: "workflow_run_id",
            status: "status",
            trigger: {
                source: "source",
                provider: "provider",
                event_name: "event_name",
                delivery_id: "delivery_id",
                payload: { key: "value" },
            },
            region: "region",
            run_params: { key: "value" },
            result_payload: { key: "value" },
            error_message: "error_message",
            iteration_count: 1,
            budget_used_usd: "budget_used_usd",
            retry: { stage_name: "stage_name" },
            stages: [
                {
                    stage_name: "stage_name",
                    stage_order: 1,
                    iteration: 1,
                    status: "status",
                    outcome: "outcome",
                    job_run_id: "job_run_id",
                    started_at: "2024-01-15T09:30:00Z",
                    completed_at: "2024-01-15T09:30:00Z",
                    artifact_count: 1,
                    input_payload: { key: "value" },
                    result_payload: { key: "value" },
                    artifacts: [{ key: "value" }],
                },
            ],
            failure: {
                code: "manifest_no_stages",
                domain: "platform",
                error_code: "error_code",
                failure_class: "failure_class",
                error_message: "error_message",
                error_details: { key: "value" },
                stage_name: "stage_name",
                stage_step: "stage_step",
                task_name: "task_name",
            },
            started_at: "2024-01-15T09:30:00Z",
            completed_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/factory/lines/name/runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.triggerFactoryLineRun({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("trigger_factory_line_run (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/factory/lines/name/runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.triggerFactoryLineRun({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_factory_line_runs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                line_name: "line_name",
                line_version_id: "line_version_id",
                status: "status",
                trigger: {
                    source: "source",
                    provider: "provider",
                    event_name: "event_name",
                    delivery_id: "delivery_id",
                    payload: { key: "value" },
                },
                region: "region",
                run_params: { key: "value" },
                stages: [{ stage_name: "stage_name", stage_order: 1, iteration: 1, status: "status" }],
                artifact_count: 1,
                artifacts: [{}],
                error_message: "error_message",
                failure: {
                    code: "manifest_no_stages",
                    domain: "platform",
                    error_code: "error_code",
                    failure_class: "failure_class",
                    error_message: "error_message",
                    error_details: { key: "value" },
                    stage_name: "stage_name",
                    stage_step: "stage_step",
                    task_name: "task_name",
                },
                started_at: "2024-01-15T09:30:00Z",
                completed_at: "2024-01-15T09:30:00Z",
                created_at: "2024-01-15T09:30:00Z",
            },
        ];

        server.mockEndpoint().get("/factory/line-runs").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.factory.listFactoryLineRuns();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_factory_line_runs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/factory/line-runs").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.factory.listFactoryLineRuns();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_factory_line_run (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            line_name: "line_name",
            line_version_id: "line_version_id",
            workflow_run_id: "workflow_run_id",
            status: "status",
            trigger: {
                source: "source",
                provider: "provider",
                event_name: "event_name",
                delivery_id: "delivery_id",
                payload: { key: "value" },
            },
            region: "region",
            run_params: { key: "value" },
            result_payload: { key: "value" },
            error_message: "error_message",
            iteration_count: 1,
            budget_used_usd: "budget_used_usd",
            retry: { stage_name: "stage_name" },
            stages: [
                {
                    stage_name: "stage_name",
                    stage_order: 1,
                    iteration: 1,
                    status: "status",
                    outcome: "outcome",
                    job_run_id: "job_run_id",
                    started_at: "2024-01-15T09:30:00Z",
                    completed_at: "2024-01-15T09:30:00Z",
                    artifact_count: 1,
                    input_payload: { key: "value" },
                    result_payload: { key: "value" },
                    artifacts: [{ key: "value" }],
                },
            ],
            failure: {
                code: "manifest_no_stages",
                domain: "platform",
                error_code: "error_code",
                failure_class: "failure_class",
                error_message: "error_message",
                error_details: { key: "value" },
                stage_name: "stage_name",
                stage_step: "stage_step",
                task_name: "task_name",
            },
            started_at: "2024-01-15T09:30:00Z",
            completed_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/factory/line-runs/run_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.getFactoryLineRun({
            run_id: "run_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_factory_line_run (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/line-runs/run_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.getFactoryLineRun({
                run_id: "run_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_factory_line_run_debug (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            line_name: "line_name",
            line_version_id: "line_version_id",
            status: "status",
            triggered_by: "triggered_by",
            region: "region",
            started_at: "2024-01-15T09:30:00Z",
            completed_at: "2024-01-15T09:30:00Z",
            error_message: "error_message",
            failure_summary: {
                stage_name: "stage_name",
                step_name: "step_name",
                failure_class: "failure_class",
                error_code: "error_code",
                error_message: "error_message",
                error_details: { key: "value" },
                compute_command_id: "compute_command_id",
            },
            stages: [
                {
                    stage_name: "stage_name",
                    stage_order: 1,
                    iteration: 1,
                    status: "status",
                    outcome: "outcome",
                    reason: "reason",
                    job_run_id: "job_run_id",
                    job_version_id: "job_version_id",
                    steps: [{}],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/factory/line-runs/run_id/debug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.getFactoryLineRunDebug({
            run_id: "run_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_factory_line_run_debug (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/line-runs/run_id/debug")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.getFactoryLineRunDebug({
                run_id: "run_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("get_factory_line_run_debug (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/line-runs/run_id/debug")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.getFactoryLineRunDebug({
                run_id: "run_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_factory_line_schedule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { cron: "cron", timezone: "timezone", enabled: true, schedule_generation: 1 };

        server
            .mockEndpoint()
            .get("/factory/lines/name/schedule")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.getFactoryLineSchedule({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_factory_line_schedule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/factory/lines/name/schedule")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.getFactoryLineSchedule({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("upsert_factory_line_schedule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { cron: "cron" };
        const rawResponseBody = { cron: "cron", timezone: "timezone", enabled: true, schedule_generation: 1 };

        server
            .mockEndpoint()
            .put("/factory/lines/name/schedule")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.factory.upsertFactoryLineSchedule({
            name: "name",
            cron: "cron",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upsert_factory_line_schedule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { cron: "cron" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/factory/lines/name/schedule")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.upsertFactoryLineSchedule({
                name: "name",
                cron: "cron",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_factory_line_schedule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/factory/lines/name/schedule").respondWith().statusCode(200).build();

        const response = await client.factory.deleteFactoryLineSchedule({
            name: "name",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_factory_line_schedule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/factory/lines/name/schedule")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.factory.deleteFactoryLineSchedule({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
