// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { IsloApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GatewayInternalClient", () => {
    test("get_sandbox_policy (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/internal/gateway/sandbox/sandbox_id/policy")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayInternal.getSandboxPolicy({
            sandbox_id: "sandbox_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_sandbox_policy (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/internal/gateway/sandbox/sandbox_id/policy")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayInternal.getSandboxPolicy({
                sandbox_id: "sandbox_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_gateway_token (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/internal/gateway/token")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayInternal.getGatewayToken({
            provider_key: "provider_key",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_gateway_token (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/internal/gateway/token")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayInternal.getGatewayToken({
                provider_key: "provider_key",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
