// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { IsloApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GatewayProfilesClient", () => {
    test("list_gateway_profiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                description: "description",
                default_action: "default_action",
                internet_enabled: true,
                is_default: true,
                rule_count: 1,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        ];

        server.mockEndpoint().get("/gateway/profiles").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.gatewayProfiles.listGatewayProfiles();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_gateway_profiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server.mockEndpoint().get("/gateway/profiles").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.gatewayProfiles.listGatewayProfiles();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_gateway_profiles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/gateway/profiles").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.gatewayProfiles.listGatewayProfiles();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("create_gateway_profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            default_action: "default_action",
            internet_enabled: true,
            is_default: true,
            rule_count: 1,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/gateway/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayProfiles.createGatewayProfile({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_gateway_profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/gateway/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.createGatewayProfile({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_gateway_profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/gateway/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.createGatewayProfile({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("create_gateway_profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/gateway/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.createGatewayProfile({
                name: "x",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_gateway_profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            default_action: "default_action",
            internet_enabled: true,
            is_default: true,
            rule_count: 1,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            rules: [
                {
                    id: "id",
                    priority: 1,
                    host_pattern: "host_pattern",
                    path_pattern: "path_pattern",
                    methods: ["methods"],
                    action: "action",
                    rate_limit_rpm: 1,
                    provider_key: "provider_key",
                    auth_strategy: { key: "value" },
                    content_filter: { key: "value" },
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayProfiles.getGatewayProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_gateway_profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.getGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("get_gateway_profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.getGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("get_gateway_profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.getGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_gateway_profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/gateway/profiles/profile_id").respondWith().statusCode(200).build();

        const response = await client.gatewayProfiles.deleteGatewayProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_gateway_profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("delete_gateway_profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("delete_gateway_profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("delete_gateway_profile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("update_gateway_profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            default_action: "default_action",
            internet_enabled: true,
            is_default: true,
            rule_count: 1,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayProfiles.updateGatewayProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_gateway_profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("update_gateway_profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("update_gateway_profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("update_gateway_profile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("create_gateway_rule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { host_pattern: "host_pattern" };
        const rawResponseBody = {
            id: "id",
            priority: 1,
            host_pattern: "host_pattern",
            path_pattern: "path_pattern",
            methods: ["methods"],
            action: "action",
            rate_limit_rpm: 1,
            provider_key: "provider_key",
            auth_strategy: { key: "value" },
            content_filter: { key: "value" },
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayProfiles.createGatewayRule({
            profile_id: "profile_id",
            host_pattern: "host_pattern",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_gateway_rule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { host_pattern: "x" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.createGatewayRule({
                profile_id: "profile_id",
                host_pattern: "x",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_gateway_rule (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { host_pattern: "x" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.createGatewayRule({
                profile_id: "profile_id",
                host_pattern: "x",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("create_gateway_rule (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { host_pattern: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.createGatewayRule({
                profile_id: "profile_id",
                host_pattern: "x",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_gateway_rule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id/rules/rule_id")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.gatewayProfiles.deleteGatewayRule({
            profile_id: "profile_id",
            rule_id: "rule_id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_gateway_rule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id/rules/rule_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayRule({
                profile_id: "profile_id",
                rule_id: "rule_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("delete_gateway_rule (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id/rules/rule_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayRule({
                profile_id: "profile_id",
                rule_id: "rule_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("delete_gateway_rule (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/gateway/profiles/profile_id/rules/rule_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.deleteGatewayRule({
                profile_id: "profile_id",
                rule_id: "rule_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("update_gateway_rule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            priority: 1,
            host_pattern: "host_pattern",
            path_pattern: "path_pattern",
            methods: ["methods"],
            action: "action",
            rate_limit_rpm: 1,
            provider_key: "provider_key",
            auth_strategy: { key: "value" },
            content_filter: { key: "value" },
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id/rules/rule_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayProfiles.updateGatewayRule({
            profile_id: "profile_id",
            rule_id: "rule_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_gateway_rule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id/rules/rule_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayRule({
                profile_id: "profile_id",
                rule_id: "rule_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("update_gateway_rule (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id/rules/rule_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayRule({
                profile_id: "profile_id",
                rule_id: "rule_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("update_gateway_rule (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/gateway/profiles/profile_id/rules/rule_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.updateGatewayRule({
                profile_id: "profile_id",
                rule_id: "rule_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("reorder_gateway_rules (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { rules: [{ rule_id: "rule_id", priority: 1 }] };
        const rawResponseBody = [
            {
                id: "id",
                priority: 1,
                host_pattern: "host_pattern",
                path_pattern: "path_pattern",
                methods: ["methods"],
                action: "action",
                rate_limit_rpm: 1,
                provider_key: "provider_key",
                auth_strategy: { key: "value" },
                content_filter: { key: "value" },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gatewayProfiles.reorderGatewayRules({
            profile_id: "profile_id",
            rules: [
                {
                    rule_id: "rule_id",
                    priority: 1,
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("reorder_gateway_rules (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            rules: [
                { rule_id: "rule_id", priority: 1 },
                { rule_id: "rule_id", priority: 1 },
            ],
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.reorderGatewayRules({
                profile_id: "profile_id",
                rules: [
                    {
                        rule_id: "rule_id",
                        priority: 1,
                    },
                    {
                        rule_id: "rule_id",
                        priority: 1,
                    },
                ],
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("reorder_gateway_rules (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            rules: [
                { rule_id: "rule_id", priority: 1 },
                { rule_id: "rule_id", priority: 1 },
            ],
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.reorderGatewayRules({
                profile_id: "profile_id",
                rules: [
                    {
                        rule_id: "rule_id",
                        priority: 1,
                    },
                    {
                        rule_id: "rule_id",
                        priority: 1,
                    },
                ],
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("reorder_gateway_rules (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IsloApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            rules: [
                { rule_id: "rule_id", priority: 1 },
                { rule_id: "rule_id", priority: 1 },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/gateway/profiles/profile_id/rules/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gatewayProfiles.reorderGatewayRules({
                profile_id: "profile_id",
                rules: [
                    {
                        rule_id: "rule_id",
                        priority: 1,
                    },
                    {
                        rule_id: "rule_id",
                        priority: 1,
                    },
                ],
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
