// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("IntegrationsClient", () => {
    test("list_integrations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    auth_method: "oauth",
                    connected: true,
                    display_name: "display_name",
                    level: "user",
                    preset_id: "preset_id",
                    provider: "provider",
                },
            ],
            next_cursor: "next_cursor",
            total: 1,
        };

        server.mockEndpoint().get("/integrations").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.integrations.listIntegrations();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_integrations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server.mockEndpoint().get("/integrations").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.integrations.listIntegrations();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_integrations (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server.mockEndpoint().get("/integrations").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.integrations.listIntegrations();
        }).rejects.toThrow(IsloApi.ForbiddenError);
    });

    test("list_integrations (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/integrations").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.integrations.listIntegrations();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_custom_services (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [{ auth_method: "oauth", name: "name", slug: "slug" }],
            next_cursor: "next_cursor",
            total: 1,
        };

        server
            .mockEndpoint()
            .get("/integrations/custom-services")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.listCustomServices();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_custom_services (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/integrations/custom-services")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.listCustomServices();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_custom_services (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/integrations/custom-services")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.listCustomServices();
        }).rejects.toThrow(IsloApi.ForbiddenError);
    });

    test("list_custom_services (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/custom-services")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.listCustomServices();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("create_custom_service (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { custom: { name: "name", slug: "slug" } };
        const rawResponseBody = { app_id: "app_id", auth_method: "oauth", name: "name", slug: "slug" };

        server
            .mockEndpoint()
            .post("/integrations/custom-services")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.createCustomService({
            custom: {
                name: "name",
                slug: "slug",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_custom_service (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { custom: { name: "name", slug: "slug" } };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/integrations/custom-services")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.createCustomService({
                custom: {
                    name: "name",
                    slug: "slug",
                },
            });
        }).rejects.toThrow(IsloApi.BadRequestError);
    });

    test("create_custom_service (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { custom: { name: "name", slug: "slug" } };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/integrations/custom-services")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.createCustomService({
                custom: {
                    name: "name",
                    slug: "slug",
                },
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_custom_service (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { custom: { name: "name", slug: "slug" } };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/integrations/custom-services")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.createCustomService({
                custom: {
                    name: "name",
                    slug: "slug",
                },
            });
        }).rejects.toThrow(IsloApi.ForbiddenError);
    });

    test("create_custom_service (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { custom: { name: "name", slug: "slug" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/integrations/custom-services")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.createCustomService({
                custom: {
                    name: "name",
                    slug: "slug",
                },
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("disconnect_custom_integration (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/integrations/custom/provider")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.disconnectCustomIntegration({
            provider: "provider",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("disconnect_custom_integration (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/integrations/custom/provider")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectCustomIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.BadRequestError);
    });

    test("disconnect_custom_integration (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/integrations/custom/provider")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectCustomIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("disconnect_custom_integration (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/integrations/custom/provider")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectCustomIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.ForbiddenError);
    });

    test("disconnect_custom_integration (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/integrations/custom/provider")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectCustomIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("disconnect_custom_integration (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/integrations/custom/provider")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectCustomIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_integration_providers", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                { apps: [{ app_id: "app_id", auth_method: "oauth", scope: "user" }], hosts: ["hosts"], name: "name" },
            ],
            next_cursor: "next_cursor",
            total: 1,
        };

        server
            .mockEndpoint()
            .get("/integrations/providers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.listIntegrationProviders();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_integration_trigger_events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            history_window: { key: "value" },
            items: [
                {
                    complete: true,
                    effect_count: 1,
                    event_name: "event_name",
                    id: "id",
                    invocation_status: "invocation_status",
                    manager_outcome: "manager_outcome",
                    outcome: "outcome",
                    provider: "provider",
                    provider_delivery_id: "provider_delivery_id",
                    received_at: "2024-01-15T09:30:00Z",
                },
            ],
            next_cursor: "next_cursor",
            oldest_available_at: "2024-01-15T09:30:00Z",
            total: 1,
        };

        server
            .mockEndpoint({ once: false })
            .get("/integrations/trigger-events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.integrations.listIntegrationTriggerEvents();

        expect(expected.items).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.items).toEqual(nextPage.data);
    });

    test("list_integration_trigger_events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/trigger-events")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.listIntegrationTriggerEvents();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_integration_trigger_event (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            complete: true,
            effect_count: 1,
            effects: [
                {
                    delivery_id: "delivery_id",
                    factory: "factory",
                    factory_id: "factory_id",
                    failure_code: "failure_code",
                    failure_summary: "failure_summary",
                    line: "line",
                    line_id: "line_id",
                    line_run_id: "line_run_id",
                    line_version: 1,
                    line_version_id: "line_version_id",
                    status: "status",
                },
            ],
            event_name: "event_name",
            failure_code: "failure_code",
            failure_summary: "failure_summary",
            history_note: "history_note",
            history_window: { key: "value" },
            id: "id",
            invocation_status: "invocation_status",
            manager_outcome: "manager_outcome",
            manager_routing: { key: 1 },
            oldest_available_at: "2024-01-15T09:30:00Z",
            outcome: "outcome",
            payload: { key: "value" },
            payload_redacted_bytes: 1,
            payload_truncated: true,
            provider: "provider",
            provider_delivery_id: "provider_delivery_id",
            received_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/integrations/trigger-events/event_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.getIntegrationTriggerEvent({
            event_id: "event_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_integration_trigger_event (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/trigger-events/event_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.getIntegrationTriggerEvent({
                event_id: "event_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_integration_triggers", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    connected: true,
                    description: "description",
                    docs_url: "docs_url",
                    filter_operators: ["filter_operators"],
                    kind: "kind",
                    name: "name",
                    provider: "provider",
                    raw_payload_example: { key: "value" },
                    selector_schema: { key: "value" },
                    title: "title",
                },
            ],
            next_cursor: "next_cursor",
            total: 1,
        };

        server
            .mockEndpoint()
            .get("/integrations/triggers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.listIntegrationTriggers();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_connected_integration_triggers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    connected: true,
                    description: "description",
                    docs_url: "docs_url",
                    filter_operators: ["filter_operators"],
                    kind: "kind",
                    name: "name",
                    provider: "provider",
                    raw_payload_example: { key: "value" },
                    selector_schema: { key: "value" },
                    title: "title",
                },
            ],
            next_cursor: "next_cursor",
            total: 1,
        };

        server
            .mockEndpoint()
            .get("/integrations/triggers/connected")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.listConnectedIntegrationTriggers();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_connected_integration_triggers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/triggers/connected")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.listConnectedIntegrationTriggers();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_integration_trigger (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            connected: true,
            description: "description",
            docs_url: "docs_url",
            filter_operators: ["filter_operators"],
            kind: "kind",
            name: "name",
            provider: "provider",
            raw_payload_example: { key: "value" },
            selector_schema: { key: "value" },
            title: "title",
        };

        server
            .mockEndpoint()
            .get("/integrations/triggers/provider/trigger_name")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.getIntegrationTrigger({
            provider: "provider",
            trigger_name: "trigger_name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_integration_trigger (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/triggers/provider/trigger_name")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.getIntegrationTrigger({
                provider: "provider",
                trigger_name: "trigger_name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_integration_status (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            provider: "provider",
            tenant: {
                connected: true,
                connected_at: "connected_at",
                email: "email",
                scopes: ["scopes"],
                username: "username",
            },
            user: {
                connected: true,
                connected_at: "connected_at",
                email: "email",
                scopes: ["scopes"],
                username: "username",
            },
        };

        server
            .mockEndpoint()
            .get("/integrations/provider")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.getIntegrationStatus({
            provider: "provider",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_integration_status (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/integrations/provider")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.getIntegrationStatus({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("get_integration_status (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/integrations/provider")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.getIntegrationStatus({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.ForbiddenError);
    });

    test("get_integration_status (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/provider")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.getIntegrationStatus({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("get_integration_status (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/integrations/provider")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.getIntegrationStatus({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("disconnect_integration (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/integrations/provider")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.disconnectIntegration({
            provider: "provider",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("disconnect_integration (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/integrations/provider")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.BadRequestError);
    });

    test("disconnect_integration (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/integrations/provider")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("disconnect_integration (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .delete("/integrations/provider")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.ForbiddenError);
    });

    test("disconnect_integration (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/integrations/provider")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("disconnect_integration (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            apiVersion: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/integrations/provider")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.integrations.disconnectIntegration({
                provider: "provider",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
