// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("JobsClient", () => {
    test("validate_job_manifest (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { manifest: { job: { name: "name" }, run: { tasks: [{ name: "name", steps: [{}] }] } } };

        server
            .mockEndpoint()
            .post("/jobs/name/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.jobs.validateJobManifest({
            name: "name",
            body: {
                manifest: {
                    job: {
                        name: "name",
                    },
                    run: {
                        tasks: [
                            {
                                name: "name",
                                steps: [{}],
                            },
                        ],
                    },
                },
            },
        });
        expect(response).toEqual(undefined);
    });

    test("validate_job_manifest (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                job: { name: "name" },
                run: {
                    tasks: [
                        { name: "name", steps: [{}, {}] },
                        { name: "name", steps: [{}, {}] },
                    ],
                },
            },
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/jobs/name/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.validateJobManifest({
                name: "name",
                body: {
                    manifest: {
                        job: {
                            name: "name",
                        },
                        run: {
                            tasks: [
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                            ],
                        },
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("validate_job_manifest (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                job: { name: "name" },
                run: {
                    tasks: [
                        { name: "name", steps: [{}, {}] },
                        { name: "name", steps: [{}, {}] },
                    ],
                },
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/jobs/name/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.validateJobManifest({
                name: "name",
                body: {
                    manifest: {
                        job: {
                            name: "name",
                        },
                        run: {
                            tasks: [
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                            ],
                        },
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("deploy_job (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { manifest: { job: { name: "name" }, run: { tasks: [{ name: "name", steps: [{}] }] } } };
        const rawResponseBody = {
            id: "id",
            version_number: 1,
            content_hash: "content_hash",
            deployed_at: "2024-01-15T09:30:00Z",
            manifest: {
                job: { name: "name", version: "version", description: "description" },
                run: {
                    fail_fast: true,
                    fanout: true,
                    concurrency: 1,
                    workdir: "workdir",
                    timeout: "timeout",
                    region: "region",
                    teardown_on_complete: true,
                    resume_on_start: true,
                    tasks: [{ name: "name", steps: [{}] }],
                },
                schedule: { cron: "cron", timezone: "timezone", enabled: true },
                verification: { enabled: true },
            },
        };

        server
            .mockEndpoint()
            .post("/jobs/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.deployJob({
            name: "name",
            body: {
                manifest: {
                    job: {
                        name: "name",
                    },
                    run: {
                        tasks: [
                            {
                                name: "name",
                                steps: [{}],
                            },
                        ],
                    },
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deploy_job (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                job: { name: "name" },
                run: {
                    tasks: [
                        { name: "name", steps: [{}, {}] },
                        { name: "name", steps: [{}, {}] },
                    ],
                },
            },
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/jobs/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.deployJob({
                name: "name",
                body: {
                    manifest: {
                        job: {
                            name: "name",
                        },
                        run: {
                            tasks: [
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                            ],
                        },
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("deploy_job (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                job: { name: "name" },
                run: {
                    tasks: [
                        { name: "name", steps: [{}, {}] },
                        { name: "name", steps: [{}, {}] },
                    ],
                },
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/jobs/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.deployJob({
                name: "name",
                body: {
                    manifest: {
                        job: {
                            name: "name",
                        },
                        run: {
                            tasks: [
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                            ],
                        },
                    },
                },
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("deploy_job (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                job: { name: "name" },
                run: {
                    tasks: [
                        { name: "name", steps: [{}, {}] },
                        { name: "name", steps: [{}, {}] },
                    ],
                },
            },
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/jobs/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.deployJob({
                name: "name",
                body: {
                    manifest: {
                        job: {
                            name: "name",
                        },
                        run: {
                            tasks: [
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                            ],
                        },
                    },
                },
            });
        }).rejects.toThrow(IsloApi.BadGatewayError);
    });

    test("deploy_job (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {
            manifest: {
                job: { name: "name" },
                run: {
                    tasks: [
                        { name: "name", steps: [{}, {}] },
                        { name: "name", steps: [{}, {}] },
                    ],
                },
            },
        };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/jobs/name/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.deployJob({
                name: "name",
                body: {
                    manifest: {
                        job: {
                            name: "name",
                        },
                        run: {
                            tasks: [
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                                {
                                    name: "name",
                                    steps: [{}, {}],
                                },
                            ],
                        },
                    },
                },
            });
        }).rejects.toThrow(IsloApi.ServiceUnavailableError);
    });

    test("get_job (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            latest_version: {
                id: "id",
                version_number: 1,
                content_hash: "content_hash",
                deployed_at: "2024-01-15T09:30:00Z",
                manifest: {
                    job: { name: "name" },
                    run: { tasks: [{ name: "name", steps: [{}] }] },
                    schedule: { cron: "cron" },
                },
            },
            params: [
                {
                    name: "name",
                    type: "type",
                    required: true,
                    default: { key: "value" },
                    description: "description",
                    pattern: "pattern",
                    prefix: "prefix",
                },
            ],
            created_at: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/jobs/name").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.getJob({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_job (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/jobs/name").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.getJob({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_job (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/jobs/name").respondWith().statusCode(200).build();

        const response = await client.jobs.deleteJob({
            name: "name",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_job (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/jobs/name").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.deleteJob({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_jobs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            { id: "id", name: "name", latest_version_number: 1, created_at: "2024-01-15T09:30:00Z" },
        ];

        server.mockEndpoint().get("/jobs").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.listJobs();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_jobs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobs();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_job_versions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                version_number: 1,
                content_hash: "content_hash",
                deployed_at: "2024-01-15T09:30:00Z",
                manifest: {
                    job: { name: "name" },
                    run: { tasks: [{ name: "name", steps: [{}] }] },
                    schedule: { cron: "cron" },
                },
            },
        ];

        server
            .mockEndpoint()
            .get("/jobs/name/versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.listJobVersions({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_job_versions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/jobs/name/versions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.listJobVersions({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_job_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            version_number: 1,
            content_hash: "content_hash",
            deployed_at: "2024-01-15T09:30:00Z",
            manifest: {
                job: { name: "name", version: "version", description: "description" },
                run: {
                    fail_fast: true,
                    fanout: true,
                    concurrency: 1,
                    workdir: "workdir",
                    timeout: "timeout",
                    region: "region",
                    teardown_on_complete: true,
                    resume_on_start: true,
                    tasks: [{ name: "name", steps: [{}] }],
                },
                schedule: { cron: "cron", timezone: "timezone", enabled: true },
                verification: { enabled: true },
            },
        };

        server
            .mockEndpoint()
            .get("/jobs/name/versions/version_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobVersion({
            name: "name",
            version_id: "version_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_job_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/jobs/name/versions/version_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobVersion({
                name: "name",
                version_id: "version_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("list_job_runs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                job_name: "job_name",
                job_version_id: "job_version_id",
                status: "status",
                region: "region",
                run_params: { key: "value" },
                step_timeline: [{ name: "name", action: "action", status: "status", task_name: "task_name" }],
                artifact_refs: [{ key: "value" }],
                started_at: "2024-01-15T09:30:00Z",
                completed_at: "2024-01-15T09:30:00Z",
                error_message: "error_message",
                error_code: "error_code",
                error_details: { key: "value" },
                created_at: "2024-01-15T09:30:00Z",
            },
        ];

        server.mockEndpoint().get("/jobs/name/runs").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.listJobRuns({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_job_runs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/jobs/name/runs").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobRuns({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("trigger_job_run (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            job_name: "job_name",
            job_version_id: "job_version_id",
            status: "status",
            region: "region",
            run_params: { key: "value" },
            step_timeline: [
                {
                    name: "name",
                    action: "action",
                    status: "status",
                    task_name: "task_name",
                    started_at: "2024-01-15T09:30:00Z",
                    completed_at: "2024-01-15T09:30:00Z",
                    error_message: "error_message",
                    error_code: "error_code",
                    error_details: { key: "value" },
                    compute_command_id: "compute_command_id",
                },
            ],
            artifact_refs: [{ key: "value" }],
            started_at: "2024-01-15T09:30:00Z",
            completed_at: "2024-01-15T09:30:00Z",
            error_message: "error_message",
            error_code: "error_code",
            error_details: { key: "value" },
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/jobs/name/runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.triggerJobRun({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("trigger_job_run (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/jobs/name/runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.triggerJobRun({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_job_run (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            job_name: "job_name",
            job_version_id: "job_version_id",
            status: "status",
            region: "region",
            run_params: { key: "value" },
            step_timeline: [
                {
                    name: "name",
                    action: "action",
                    status: "status",
                    task_name: "task_name",
                    started_at: "2024-01-15T09:30:00Z",
                    completed_at: "2024-01-15T09:30:00Z",
                    error_message: "error_message",
                    error_code: "error_code",
                    error_details: { key: "value" },
                    compute_command_id: "compute_command_id",
                },
            ],
            artifact_refs: [{ key: "value" }],
            started_at: "2024-01-15T09:30:00Z",
            completed_at: "2024-01-15T09:30:00Z",
            error_message: "error_message",
            error_code: "error_code",
            error_details: { key: "value" },
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/jobs/name/runs/run_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobRun({
            name: "name",
            run_id: "run_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_job_run (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/jobs/name/runs/run_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobRun({
                name: "name",
                run_id: "run_id",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("get_job_schedule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { cron: "cron", timezone: "timezone", enabled: true, schedule_generation: 1 };

        server
            .mockEndpoint()
            .get("/jobs/name/schedule")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobSchedule({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_job_schedule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/jobs/name/schedule")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobSchedule({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });

    test("delete_job_schedule (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/jobs/name/schedule").respondWith().statusCode(200).build();

        const response = await client.jobs.deleteJobSchedule({
            name: "name",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_job_schedule (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/jobs/name/schedule")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.deleteJobSchedule({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
