// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SessionsClient", () => {
    test("sandbox_attach_session (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server
            .mockEndpoint()
            .get("/sandboxes/sandbox_name/sessions/session/attach")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.sessions.sandboxAttachSession({
            sandbox_name: "sandbox_name",
            session: "session",
        });
        expect(response).toEqual(undefined);
    });

    test("sandbox_attach_session (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/sandboxes/sandbox_name/sessions/session/attach")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.sandboxAttachSession({
                sandbox_name: "sandbox_name",
                session: "session",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("sandbox_attach_session (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .get("/sandboxes/sandbox_name/sessions/session/attach")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.sandboxAttachSession({
                sandbox_name: "sandbox_name",
                session: "session",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });
});
