// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockIsloAccessKey } from "./mockAuth";

describe("SharesClient", () => {
    test("list_shares (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = [
            { created_at: "created_at", expires_at: "expires_at", port: 1, share_id: "share_id", url: "url" },
        ];

        server
            .mockEndpoint()
            .get("/sandboxes/name/shares")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.listShares({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_shares (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .get("/sandboxes/name/shares")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.listShares({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_shares (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .get("/sandboxes/name/shares")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.listShares({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("create_share (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { port: 1 };
        const rawResponseBody = {
            created_at: "created_at",
            expires_at: "expires_at",
            port: 1,
            share_id: "share_id",
            url: "url",
        };

        server
            .mockEndpoint()
            .post("/sandboxes/name/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.createShare({
            name: "name",
            port: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_share (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { port: 1 };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/sandboxes/name/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.createShare({
                name: "name",
                port: 1,
            });
        }).rejects.toThrow(IsloApi.BadRequestError);
    });

    test("create_share (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { port: 1 };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/sandboxes/name/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.createShare({
                name: "name",
                port: 1,
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_share (4)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { port: 1 };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/sandboxes/name/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.createShare({
                name: "name",
                port: 1,
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("delete_share (1)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/sandboxes/name/shares/share_id").respondWith().statusCode(200).build();

        const response = await client.shares.deleteShare({
            name: "name",
            share_id: "share_id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_share (2)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .delete("/sandboxes/name/shares/share_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.deleteShare({
                name: "name",
                share_id: "share_id",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("delete_share (3)", async () => {
        const server = mockServerPool.createServer();
        mockIsloAccessKey(server);

        const client = new Islo({
            maxRetries: 0,
            clientId: "access_key",
            clientSecret: "test_client_secret",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .delete("/sandboxes/name/shares/share_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.deleteShare({
                name: "name",
                share_id: "share_id",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });
});
