// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SnapshotsClient", () => {
    test("list_snapshots (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    checksum_sha256: "checksum_sha256",
                    created_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    id: "id",
                    name: "name",
                    sandbox_id: "sandbox_id",
                    size_bytes: 1000000,
                    status: "status",
                },
            ],
            limit: 1,
            offset: 1,
            total: 1000000,
        };

        server.mockEndpoint().get("/snapshots/").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.snapshots.listSnapshots();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_snapshots (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().get("/snapshots/").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.snapshots.listSnapshots();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_snapshot (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { sandbox_name: "sandbox_name" };
        const rawResponseBody = {
            checksum_sha256: "checksum_sha256",
            created_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            id: "id",
            name: "name",
            sandbox_id: "sandbox_id",
            size_bytes: 1000000,
            status: "status",
        };

        server
            .mockEndpoint()
            .post("/snapshots/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.snapshots.createSnapshot({
            sandbox_name: "sandbox_name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_snapshot (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { sandbox_name: "sandbox_name" };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/snapshots/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.snapshots.createSnapshot({
                sandbox_name: "sandbox_name",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("create_snapshot (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { sandbox_name: "sandbox_name" };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/snapshots/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.snapshots.createSnapshot({
                sandbox_name: "sandbox_name",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("create_snapshot (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { sandbox_name: "sandbox_name" };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/snapshots/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.snapshots.createSnapshot({
                sandbox_name: "sandbox_name",
            });
        }).rejects.toThrow(IsloApi.ConflictError);
    });

    test("create_snapshot (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });
        const rawRequestBody = { sandbox_name: "sandbox_name" };
        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server
            .mockEndpoint()
            .post("/snapshots/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.snapshots.createSnapshot({
                sandbox_name: "sandbox_name",
            });
        }).rejects.toThrow(IsloApi.ServiceUnavailableError);
    });

    test("get_snapshot (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            checksum_sha256: "checksum_sha256",
            created_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            id: "id",
            name: "name",
            sandbox_id: "sandbox_id",
            size_bytes: 1000000,
            status: "status",
        };

        server.mockEndpoint().get("/snapshots/name").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.snapshots.getSnapshot({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_snapshot (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().get("/snapshots/name").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.snapshots.getSnapshot({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("get_snapshot (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().get("/snapshots/name").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.snapshots.getSnapshot({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });

    test("delete_snapshot (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        server.mockEndpoint().delete("/snapshots/name").respondWith().statusCode(200).build();

        const response = await client.snapshots.deleteSnapshot({
            name: "name",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_snapshot (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().delete("/snapshots/name").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.snapshots.deleteSnapshot({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("delete_snapshot (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().delete("/snapshots/name").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.snapshots.deleteSnapshot({
                name: "name",
            });
        }).rejects.toThrow(IsloApi.NotFoundError);
    });
});
