// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TenantsClient", () => {
    test("list_tenant_compute_regions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = {
            regions: [{ key: "key", label: "label", api_url: "api_url", ws_url: "ws_url", is_default: true }],
        };

        server.mockEndpoint().get("/tenants/regions").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tenants.listTenantComputeRegions();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_tenant_compute_regions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { code: "UNAUTHORIZED", message: "message" };

        server.mockEndpoint().get("/tenants/regions").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenants.listTenantComputeRegions();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("list_tenant_compute_regions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({
            maxRetries: 0,
            apiKey: "test",
            environment: { control: server.baseUrl, compute: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/tenants/regions").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenants.listTenantComputeRegions();
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
