// This file was auto-generated by Fern from our API Definition.

import * as IsloApi from "../../src/api/index";
import { Islo } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsersClient", () => {
    test("authorize_user (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/users/authorize").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.authorizeUser();
        expect(response).toEqual(rawResponseBody);
    });

    test("authorize_user (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server.mockEndpoint().post("/users/authorize").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.authorizeUser();
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("invite_user (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { email: "email", message: "message" };

        server
            .mockEndpoint()
            .post("/users/invite")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.inviteUser({
            email: "email",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("invite_user (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { code: "AUTH_REQUIRED", message: "message" };

        server
            .mockEndpoint()
            .post("/users/invite")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.inviteUser({
                email: "email",
            });
        }).rejects.toThrow(IsloApi.UnauthorizedError);
    });

    test("invite_user (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Islo({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/users/invite")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.inviteUser({
                email: "email",
            });
        }).rejects.toThrow(IsloApi.UnprocessableEntityError);
    });
});
