// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         amount_cents: 1
 *     }
 */
export interface CreateCheckoutRequest {
    amount_cents: number;
}
