// This file was auto-generated by Fern from our API Definition.

export const ListKnowledgeVersionsRequestSort = {
    VersionNumber: "version_number",
} as const;
export type ListKnowledgeVersionsRequestSort =
    (typeof ListKnowledgeVersionsRequestSort)[keyof typeof ListKnowledgeVersionsRequestSort];
