// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         factory_id: "factory_id",
 *         item: "item"
 *     }
 */
export interface BodyCreateFactoryKnowledgeMedia {
    factory_id: string;
    /** JSON metadata for the knowledge item */
    item: string;
    /** Media file */
    file: core.file.Uploadable;
}
