// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         factory_id: "factory_id"
 *     }
 */
export interface FactoryUpdate {
    factory_id: string;
    name?: string | null;
    key?: string | null;
    color?: string | null;
    icon?: string | null;
    status?: IsloApi.FactoryStatus | null;
}
