// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         factory_id: "factory_id",
 *         session_name: "session_name",
 *         sandbox_id: "sandbox_id"
 *     }
 */
export interface GetFactoryAgentSessionEventsRequest {
    factory_id: string;
    session_name: string;
    sandbox_id: string;
    session_path?: string | null;
    include_descendants?: boolean;
    limit?: number;
    offset?: number;
    since?: string | null;
}
