// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         factory_id: "factory_id"
 *     }
 */
export interface ListFactoryAgentSessionsRequest {
    factory_id: string;
    since?: string | null;
    include_subagents?: boolean;
    limit?: number;
    cursor?: string | null;
}
