// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         factory_id: "factory_id"
 *     }
 */
export interface ListFactoryResourceLinesRequest {
    factory_id: string;
}
