// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         factory_id: "factory_id",
 *         name: "name"
 *     }
 */
export interface ListScopedFactoryJobVersionsRequest {
    factory_id: string;
    name: string;
    limit?: number;
    offset?: number;
}
