// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         factory_id: "factory_id"
 *     }
 */
export interface ListFactoryKnowledgeRequest {
    factory_id: string;
    level?: IsloApi.KnowledgeLevel | null;
    type?: IsloApi.KnowledgeLevel | null;
    tag?: string | null;
    repository?: string | null;
    q?: string | null;
    cursor?: string | null;
    limit?: number;
}
