// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         factory_id: "factory_id",
 *         fields: ["fields"]
 *     }
 */
export interface ListFactoryKnowledgeFacetsRequest {
    factory_id: string;
    fields?: string | string[];
}
