// This file was auto-generated by Fern from our API Definition.

import type * as IsloApi from "../../../../index.js";

/**
 * @example
 *     {
 *         factory_id: "factory_id",
 *         run_id: "run_id",
 *         body: {}
 *     }
 */
export interface StopScopedFactoryLineRunRequest {
    factory_id: string;
    run_id: string;
    body: IsloApi.LineRunControlRequest;
}
